"""
Module: auto_开发基于sim_to_real的域随机化_3d44a5
Description: Sim-to-Real Domain Randomization Adapter.
             Automatically calculates residuals between simulated physics parameters
             and real-world sensor streams to optimize transfer learning performance.
Author: AGI System
Version: 1.0.0
"""

import logging
import numpy as np
from typing import Dict, Tuple, Optional, List
from dataclasses import dataclass

# Configuring logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

@dataclass
class PhysicsParameters:
    """Data class representing physics parameters for simulation or real world."""
    mass: float  # kg
    friction: float  # coefficient
    damping: float  # Ns/m
    latency: float  # seconds

    def to_vector(self) -> np.ndarray:
        """Converts parameters to a numpy vector for calculation."""
        return np.array([self.mass, self.friction, self.damping, self.latency])

@dataclass
class SensorFrame:
    """Data class representing a frame of sensor data."""
    timestamp: float
    acceleration: np.ndarray  # [x, y, z]
    velocity: np.ndarray      # [x, y, z]
    is_valid: bool

class DomainRandomizationAdapter:
    """
    Adapts simulation parameters to reduce the reality gap using residual analysis.
    
    This class implements a feedback loop where the difference (residual) between 
    simulated behavior and real sensor data is minimized by dynamically adjusting 
    domain randomization ranges.
    """

    def __init__(self, initial_params: PhysicsParameters, bounds: Dict[str, Tuple[float, float]]):
        """
        Initialize the adapter with nominal parameters and safety bounds.
        
        Args:
            initial_params (PhysicsParameters): The nominal physics parameters.
            bounds (Dict[str, Tuple[float, float]]): Min/Max bounds for randomization.
        
        Raises:
            ValueError: If bounds are not properly defined.
        """
        self.current_params = initial_params
        self.bounds = bounds
        self.history: List[float] = []
        self.learning_rate = 0.05
        
        if not self._validate_bounds():
            raise ValueError("Invalid parameter bounds provided.")
            
        logger.info("DomainRandomizationAdapter initialized with mass=%.2f", initial_params.mass)

    def _validate_bounds(self) -> bool:
        """
        Validates that the bounds are physically plausible (min < max).
        
        Returns:
            bool: True if validation passes, False otherwise.
        """
        required_keys = ['mass', 'friction', 'damping', 'latency']
        for key in required_keys:
            if key not in self.bounds:
                logger.error(f"Missing bound for parameter: {key}")
                return False
            min_val, max_val = self.bounds[key]
            if min_val >= max_val:
                logger.error(f"Invalid bounds for {key}: min {min_val} >= max {max_val}")
                return False
        return True

    def compute_residual(self, sim_frame: SensorFrame, real_frame: SensorFrame) -> float:
        """
        Calculate the weighted residual error between simulated and real sensor frames.
        
        This function computes the L2 norm of the difference between acceleration 
        and velocity vectors, adjusting for timestamp synchronization.
        
        Args:
            sim_frame (SensorFrame): Data generated by the simulator.
            real_frame (SensorFrame): Data captured from real sensors.
            
        Returns:
            float: The computed residual error scalar.
            
        Raises:
            ValueError: If frames are invalid or time difference is too large.
        """
        if not sim_frame.is_valid or not real_frame.is_valid:
            raise ValueError("Cannot compute residual on invalid sensor frames.")
            
        # Time synchronization check
        time_diff = abs(sim_frame.timestamp - real_frame.timestamp)
        if time_diff > 0.1:
            logger.warning(f"Large time discrepancy detected: {time_diff}s")
            
        # Calculate vector differences
        acc_diff = sim_frame.acceleration - real_frame.acceleration
        vel_diff = sim_frame.velocity - real_frame.velocity
        
        # Weighted L2 norm (Acceleration usually has higher noise)
        residual = np.linalg.norm(acc_diff) * 0.7 + np.linalg.norm(vel_diff) * 0.3
        
        logger.debug(f"Computed residual: {residual:.4f}")
        return residual

    def update_randomization_params(self, current_residual: float) -> PhysicsParameters:
        """
        Update the internal physics parameters based on the gradient of the residual.
        
        Core Logic:
        If the residual is high, we expand randomization range or shift the mean
        to cover the "real" dynamics more effectively. 
        Here we implement a simplified gradient descent on the parameter mean.
        
        Args:
            current_residual (float): The error metric from `compute_residual`.
            
        Returns:
            PhysicsParameters: The updated physics parameters for the next sim iteration.
        """
        self.history.append(current_residual)
        
        # Simple adaptive logic: adjust parameters slightly based on error magnitude
        # In a full AGI system, this would use a Bayesian Optimizer or RL policy.
        adjustment = self.learning_rate * current_residual
        
        # Apply adjustment (clamped by bounds)
        new_mass = np.clip(
            self.current_params.mass + (adjustment * np.random.randn()), 
            self.bounds['mass'][0], 
            self.bounds['mass'][1]
        )
        new_friction = np.clip(
            self.current_params.friction + (adjustment * np.random.randn()), 
            self.bounds['friction'][0], 
            self.bounds['friction'][1]
        )
        
        self.current_params.mass = new_mass
        self.current_params.friction = new_friction
        
        logger.info(f"Updated params: Mass={new_mass:.3f}, Friction={new_friction:.3f}")
        return self.current_params

    def get_randomized_config(self) -> Dict[str, float]:
        """
        Generates a randomized configuration dictionary for the simulation environment
        based on the current estimated mean and predefined bounds.
        
        Returns:
            Dict[str, float]: A dictionary of physics properties for the next episode.
        """
        config = {}
        # Sample from a truncated normal distribution around current params
        for key, (min_b, max_b) in self.bounds.items():
            mean = getattr(self.current_params, key)
            std_dev = (max_b - min_b) / 4.0  # Cover range with 2 sigma
            
            val = np.random.normal(mean, std_dev)
            clipped_val = np.clip(val, min_b, max_b)
            config[key] = clipped_val
            
        logger.debug(f"Generated randomized config: {config}")
        return config

# ==========================================
# Usage Example
# ==========================================
if __name__ == "__main__":
    # Define nominal parameters and safety bounds
    nominal = PhysicsParameters(mass=1.0, friction=0.5, damping=0.1, latency=0.02)
    safety_bounds = {
        'mass': (0.8, 1.2),
        'friction': (0.3, 0.7),
        'damping': (0.05, 0.15),
        'latency': (0.01, 0.05)
    }

    # Initialize Adapter
    try:
        adapter = DomainRandomizationAdapter(nominal, safety_bounds)
        
        # Simulate a loop of Sim-to-Real adaptation
        for i in range(3):
            # 1. Get config for simulation
            sim_config = adapter.get_randomized_config()
            
            # 2. Mock Sensor Data (In reality, these come from engines/sensors)
            sim_data = SensorFrame(
                timestamp=i * 0.1,
                acceleration=np.array([1.0, 0.1, 0.0]) * sim_config['mass'],
                velocity=np.array([0.5, 0.0, 0.0]),
                is_valid=True
            )
            
            # 3. Mock Real Data (Ground Truth with noise)
            real_data = SensorFrame(
                timestamp=i * 0.1,
                acceleration=np.array([1.05, 0.12, 0.01]), # Slightly different
                velocity=np.array([0.52, 0.01, 0.0]),
                is_valid=True
            )
            
            # 4. Compute Residual
            error = adapter.compute_residual(sim_data, real_data)
            
            # 5. Adapt Parameters
            adapter.update_randomization_params(error)
            
    except Exception as e:
        logger.error(f"Runtime error in adaptation loop: {e}")