"""
Module: adaptive_compute_system.py

This module implements a dynamic resource allocation system inspired by the human brain's
"Fast and Slow Thinking" mechanism (Dual Process Theory). It optimizes computational
efficiency by routing tasks to appropriate models based on real-time difficulty assessment.

Core Logic:
1. Fast Path (System 1): Uses lightweight sparse models for simple, routine tasks.
2. Slow Path (System 2): Activates heavy MoE or Logic Verifiers for complex reasoning.

Author: AGI System Core Engineer
Version: 1.0.0
"""

import logging
import time
import random
from typing import Dict, Any, Tuple, Optional, List
from dataclasses import dataclass, field
from enum import Enum

# Configure structured logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("AdaptiveCortex")

# --- Constants and Enums ---

class ComplexityLevel(Enum):
    """Enumeration of task complexity levels."""
    TRIVIAL = 0       # System 1: Fast, automatic, low resource
    MODERATE = 1      # System 1/2 Boundary: Cached or optimized processing
    COMPLEX = 2       # System 2: Slow, effortful, high resource (MoE)

class ModelType(Enum):
    """Target execution engine types."""
    SPARSE_MODEL = "sparse_activation_v1"
    MOE_MODEL = "mixture_of_experts_v3"
    FORMAL_VERIFIER = "symbolic_logic_core"

# --- Data Structures ---

@dataclass
class TaskContext:
    """Input context for the cognitive system."""
    query_text: str
    user_profile: Dict[str, Any] = field(default_factory=dict)
    available_budget: float = 1.0  # Compute budget constraint
    
    def __post_init__(self):
        if not self.query_text:
            raise ValueError("Query text cannot be empty.")

@dataclass
class ComputePlan:
    """Execution plan generated by the system."""
    selected_model: ModelType
    estimated_latency_ms: float
    reasoning_path: str
    tokens_allocated: int
    complexity_score: float

# --- Core System Components ---

class DifficultyEstimator:
    """
    Analyzes input intent to determine computational requirements.
    Acts as the 'Thalamus' or 'Prefrontal Cortex' dispatcher.
    """

    def __init__(self, threshold_complex: float = 0.7, threshold_moderate: float = 0.4):
        self.threshold_complex = threshold_complex
        self.threshold_moderate = threshold_moderate
        self._complex_keywords = {
            'optimize', 'prove', 'analyze', 'code', 'refactor', 
            'strategy', 'calculate', 'design', 'architect'
        }

    def assess(self, context: TaskContext) -> Tuple[ComplexityLevel, float]:
        """
        Evaluates the complexity of the input task.
        
        Args:
            context (TaskContext): The input data wrapper.
            
        Returns:
            Tuple[ComplexityLevel, float]: The determined level and raw score (0.0-1.0).
        """
        score = 0.0
        text_lower = context.query_text.lower()
        
        # Heuristic 1: Keyword Density
        keyword_hits = sum(1 for word in self._complex_keywords if word in text_lower)
        score += min(keyword_hits * 0.15, 0.6)
        
        # Heuristic 2: Structural Length (proxy for information density)
        word_count = len(context.query_text.split())
        if word_count > 100:
            score += 0.2
        elif word_count > 300:
            score += 0.4
            
        # Heuristic 3: User Profile History (Mock logic)
        if context.user_profile.get('historical_error_rate', 0) > 0.2:
            score += 0.15 # Compensate for user's past confusion with deeper logic
            
        # Normalize score
        score = min(max(score, 0.0), 1.0)
        
        if score >= self.threshold_complex:
            level = ComplexityLevel.COMPLEX
        elif score >= self.threshold_moderate:
            level = ComplexityLevel.MODERATE
        else:
            level = ComplexityLevel.TRIVIAL
            
        logger.debug(f"Task assessed: Score {score:.2f}, Level {level}")
        return level, score

class AdaptiveOrchestrator:
    """
    Main controller class. It selects the execution engine based on the 
    difficulty assessment and manages the inference lifecycle.
    """

    def __init__(self):
        self.estimator = DifficultyEstimator()
        self._active_sessions = 0

    def _route_to_fast_system(self, context: TaskContext) -> ComputePlan:
        """
        Internal: Prepares execution plan for the 'Fast' path.
        Uses Sparse models (System 1).
        """
        logger.info("Routing to System 1 (Fast/Sparse)")
        return ComputePlan(
            selected_model=ModelType.SPARSE_MODEL,
            estimated_latency_ms=50 + random.randint(0, 20),
            reasoning_path="heuristic_pattern_matching",
            tokens_allocated=256,
            complexity_score=0.0
        )

    def _route_to_slow_system(self, context: TaskContext, score: float) -> ComputePlan:
        """
        Internal: Prepares execution plan for the 'Slow' path.
        Uses MoE or Logic Verification (System 2).
        """
        logger.info("Routing to System 2 (Slow/MoE)")
        
        # Decide between Creative Reasoning (MoE) or Formal Logic
        if "verify" in context.query_text.lower() or "math" in context.query_text.lower():
            model = ModelType.FORMAL_VERIFIER
            path = "symbolic_tree_search"
        else:
            model = ModelType.MOE_MODEL
            path = "chain_of_thought_decomposition"
            
        return ComputePlan(
            selected_model=model,
            estimated_latency_ms=1200 + random.randint(0, 500),
            reasoning_path=path,
            tokens_allocated=2048,
            complexity_score=score
        )

    def process_request(self, context: TaskContext) -> Dict[str, Any]:
        """
        Main entry point. Processes a cognitive request dynamically.
        
        Args:
            context (TaskContext): Validated input context.
            
        Returns:
            Dict[str, Any]: The result package containing the answer and metadata.
            
        Raises:
            RuntimeError: If the execution engine fails.
        """
        start_time = time.time()
        
        try:
            # 1. Assessment Phase
            level, score = self.estimator.assess(context)
            
            # 2. Routing Phase (The core of the Fast/Slow mechanism)
            if level == ComplexityLevel.COMPLEX:
                plan = self._route_to_slow_system(context, score)
            else:
                # Even moderate tasks can often be handled by optimized fast paths,
                # but here we strictly separate them for demonstration.
                plan = self._route_to_fast_system(context)
                
            # 3. Execution Simulation
            # (In a real scenario, this would call the model API)
            simulated_output = self._mock_execute(plan, context)
            
            latency = (time.time() - start_time) * 1000
            
            return {
                "status": "success",
                "response": simulated_output,
                "system_type": "System_2" if level == ComplexityLevel.COMPLEX else "System_1",
                "model_used": plan.selected_model.value,
                "actual_latency_ms": latency,
                "complexity_score": score
            }
            
        except Exception as e:
            logger.error(f"Orchestration failed: {str(e)}", exc_info=True)
            return {
                "status": "error",
                "message": str(e)
            }

    def _mock_execute(self, plan: ComputePlan, context: TaskContext) -> str:
        """
        Helper function to simulate model inference.
        
        Args:
            plan (ComputePlan): The execution strategy.
            context (TaskContext): Original input.
            
        Returns:
            str: Simulated response text.
        """
        # Simulate processing time
        time.sleep(plan.estimated_latency_ms / 1000.0)
        
        if plan.selected_model == ModelType.SPARSE_MODEL:
            return f"Fast response to '{context.query_text[:20]}...': Looks good."
        else:
            return f"Deep analysis of '{context.query_text[:20]}...': Verified and optimized."

# --- Usage Example ---

if __name__ == "__main__":
    # Initialize the system
    orchestrator = AdaptiveOrchestrator()
    
    # Example 1: Simple Query (Fast Path)
    simple_ctx = TaskContext(query_text="Hello, what is the time?")
    result_fast = orchestrator.process_request(simple_ctx)
    print("\n--- Fast Path Result ---")
    print(f"Model: {result_fast['model_used']}")
    print(f"Response: {result_fast['response']}")
    
    # Example 2: Complex Query (Slow Path)
    complex_ctx = TaskContext(
        query_text="Please design an algorithm to optimize supply chain logistics and prove its correctness.",
        user_profile={"historical_error_rate": 0.3}
    )
    result_slow = orchestrator.process_request(complex_ctx)
    print("\n--- Slow Path Result ---")
    print(f"Model: {result_slow['model_used']}")
    print(f"Response: {result_slow['response']}")