"""
Module: cognitive_load_interaction.py

This module implements a framework for Cognitive Load Minimization in Human-Computer
Interaction (HCI), specifically within Human-AI Symbiosis contexts.

The core objective is to quantify and minimize the cognitive effort required by a human
operator when validating AI outputs. It provides a protocol for determining the 'Minimal
Sufficient Query Set' (MSQS) — asking the fewest, most critical questions to transform
human practice into validated graph nodes without imposing structural burdens.

Author: AGI System Core Engineer
Version: 1.0.0
License: MIT
"""

import logging
import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class InteractionType(Enum):
    """Defines the types of interaction and their relative cognitive weights."""
    BINARY_CHOICE = 1.0      # Yes/No, True/False (Low Load)
    MULTI_CHOICE_3 = 1.5     # Selection from 3 options
    MULTI_CHOICE_5 = 2.0     # Selection from 5 options
    FREE_TEXT = 5.0          # Open-ended input (High Load)
    STRUCTURE_MAPPING = 8.0  # Mapping data to schema (Very High Load)


class NodeState(Enum):
    """State of the AI-generated node."""
    UNVALIDATED = 0
    VALIDATED = 1
    REJECTED = 2
    NEEDS_REVIEW = 3


@dataclass
class KnowledgeNode:
    """
    Represents a unit of information generated by the AI to be validated by humans.
    
    Attributes:
        node_id: Unique identifier.
        content: The raw data or logic of the node.
        entropy_score: Uncertainty score (0.0 to 1.0). Higher means AI is less sure.
        criticality_score: Impact score if the node is wrong (0.0 to 1.0).
        state: Current validation state.
        required_schema: Keys required to validate structure (avoids asking human to define them).
    """
    node_id: str
    content: Any
    entropy_score: float = 0.0
    criticality_score: float = 0.5
    state: NodeState = NodeState.UNVALIDATED
    required_schema: List[str] = field(default_factory=list)

    def __post_init__(self):
        """Validate data after initialization."""
        if not 0.0 <= self.entropy_score <= 1.0:
            raise ValueError("Entropy score must be between 0.0 and 1.0")
        if not 0.0 <= self.criticality_score <= 1.0:
            raise ValueError("Criticality score must be between 0.0 and 1.0")


class CognitiveLoadManager:
    """
    Manages the interaction protocol to minimize human cognitive load.
    
    This class calculates the cognitive cost of potential interactions and selects
    the optimal interaction strategy to validate nodes.
    """

    def __init__(self, human_capacity_threshold: float = 10.0):
        """
        Initialize the manager.
        
        Args:
            human_capacity_threshold: The maximum 'Cognitive Load Units' (CLU)
                                     a human should expend in a single session.
        """
        self.human_capacity_threshold = human_capacity_threshold
        self.session_load: float = 0.0
        logger.info(f"CognitiveLoadManager initialized with capacity: {human_capacity_threshold}")

    def _calculate_interaction_cost(self, interaction_type: InteractionType, 
                                    context_complexity: float = 1.0) -> float:
        """
        Helper function to calculate the cognitive cost of a specific interaction.
        
        Formula: Base_Weight * log(1 + Context_Complexity)
        
        Args:
            interaction_type: The type of question/task.
            context_complexity: A multiplier based on domain complexity.
            
        Returns:
            float: The calculated cognitive cost.
        """
        if context_complexity < 0:
            logger.warning("Negative context complexity detected, defaulting to 0")
            context_complexity = 0

        # Logarithmic scaling prevents explosion of cost while accounting for complexity
        cost = interaction_type.value * math.log(1 + context_complexity + 0.1)
        return round(cost, 2)

    def _determine_necessity(self, node: KnowledgeNode) -> Tuple[bool, float]:
        """
        Determines if human validation is actually needed based on AI confidence
        and node criticality.
        
        Args:
            node: The KnowledgeNode to evaluate.
            
        Returns:
            Tuple[bool, float]: (Is_interaction_needed, calculated_priority_score)
        """
        # If AI is very confident (low entropy) and criticality is low, auto-validate
        if node.entropy_score < 0.1 and node.criticality_score < 0.3:
            logger.info(f"Node {node.node_id}: Auto-validating (Low entropy/criticality)")
            return False, 0.0
        
        # Calculate priority: High Criticality + High Entropy = High Priority
        priority = (node.criticality_score * 0.7) + (node.entropy_score * 0.3)
        return True, priority

    def design_interaction_protocol(self, node: KnowledgeNode) -> Optional[Dict[str, Any]]:
        """
        Core Function: Designs the optimal interaction protocol for a given node.
        
        This function attempts to convert a potentially complex validation task
        into a Binary Choice interaction if possible, to minimize load.
        
        Args:
            node: The node requiring validation.
            
        Returns:
            A dictionary containing the interaction plan, or None if auto-validated.
        """
        logger.debug(f"Designing protocol for node {node.node_id}")
        
        # Step 1: Check necessity
        needed, priority = self._determine_necessity(node)
        if not needed:
            node.state = NodeState.VALIDATED
            return None

        # Step 2: Estimate complexity based on content length or schema size
        complexity = len(node.required_schema) if node.required_schema else 1.0
        
        # Step 3: Select interaction type based on Cognitive Load constraints
        # We try to default to BINARY_CHOICE to minimize load
        selected_type = InteractionType.BINARY_CHOICE
        
        # Check if we should upgrade the interaction type
        if node.entropy_score > 0.8:
            # High entropy means AI really doesn't know, might need specific input
            selected_type = InteractionType.FREE_TEXT
        
        cost = self._calculate_interaction_cost(selected_type, complexity)
        
        # Step 4: Boundary Check - Will this exhaust the human?
        if (self.session_load + cost) > self.human_capacity_threshold:
            logger.warning(f"Node {node.node_id} exceeds human capacity threshold. Deferring.")
            return {
                "status": "DEFERRED",
                "reason": "Cognitive capacity exceeded",
                "current_load": self.session_load
            }

        # Step 5: Construct the minimal payload
        # The 'Pre-structure' feature: AI fills in the structure, human just says Yes/No
        proposed_structure = {
            "summary": str(node.content)[:100] + "...",  # Truncate for display
            "suggested_schema": node.required_schema
        }

        interaction_plan = {
            "node_id": node.node_id,
            "interaction_type": selected_type.name,
            "cognitive_cost_estimated": cost,
            "priority_score": priority,
            "question": "Does this generated node correctly represent the knowledge?",
            "context": proposed_structure,
            "options": ["Confirm (Yes)", "Reject (No)", "Edit (High Load)"]
        }

        self.session_load += cost
        logger.info(f"Protocol designed for {node.node_id}. Cost: {cost}. Total Load: {self.session_load}")
        
        return interaction_plan

    def process_human_feedback(self, node: KnowledgeNode, feedback: Dict[str, Any]) -> NodeState:
        """
        Core Function: Processes human feedback and updates node state.
        
        This function ensures that the feedback loop is closed efficiently.
        
        Args:
            node: The node being validated.
            feedback: Dictionary containing 'response' and optional 'corrections'.
            
        Returns:
            The updated NodeState.
        """
        response = feedback.get("response")
        
        if response == "Confirm (Yes)":
            node.state = NodeState.VALIDATED
            logger.info(f"Node {node.node_id} VALIDATED by human.")
        elif response == "Reject (No)":
            node.state = NodeState.REJECTED
            logger.info(f"Node {node.node_id} REJECTED by human.")
        elif response == "Edit (High Load)":
            node.state = NodeState.NEEDS_REVIEW
            # If human edits, we assume the content is updated, but needs re-evaluation
            # In a real system, we would update node.content here
            logger.info(f"Node {node.node_id} marked for REVIEW (Human provided edits).")
        else:
            logger.error(f"Unknown feedback response: {response}")
            raise ValueError("Invalid feedback response provided")
            
        return node.state


# --- Usage Example ---

if __name__ == "__main__":
    # Initialize the manager
    manager = CognitiveLoadManager(human_capacity_threshold=7.5)
    
    # Scenario 1: A low-stakes node that should be auto-validated
    node_trivial = KnowledgeNode(
        node_id="n_001",
        content="The sky is blue.",
        entropy_score=0.05,
        criticality_score=0.1
    )
    
    # Scenario 2: A high-stakes, high-uncertainty node requiring interaction
    node_critical = KnowledgeNode(
        node_id="n_002",
        content="The optimal surgery path is via the left hemisphere.",
        entropy_score=0.6,
        criticality_score=0.9,
        required_schema=["anatomy", "procedure", "risk_level"]
    )
    
    # Scenario 3: A moderately complex node
    node_moderate = KnowledgeNode(
        node_id="n_003",
        content="User preference settings updated.",
        entropy_score=0.4,
        criticality_score=0.4
    )

    # Process Trivial Node
    plan1 = manager.design_interaction_protocol(node_trivial)
    print(f"Plan for Node 1 (Trivial): {plan1}")  # Should be None
    
    # Process Critical Node
    plan2 = manager.design_interaction_protocol(node_critical)
    print(f"\nPlan for Node 2 (Critical):\n{plan2}")
    
    # Process Moderate Node
    plan3 = manager.design_interaction_protocol(node_moderate)
    print(f"\nPlan for Node 3 (Moderate):\n{plan3}")
    
    # Simulate Human Feedback
    if plan2:
        print("\n--- Simulating Feedback Loop ---")
        # Simulate a confirmation
        feedback = {"response": "Confirm (Yes)"}
        final_state = manager.process_human_feedback(node_critical, feedback)
        print(f"Final state of Node 2: {final_state.name}")