"""
Module: variational_code_generator.py

Description:
    Implements a 'Variational Code Generator' for AGI systems.
    
    Instead of generating code from scratch (Zero-Shot), this system identifies 
    'Themes' (verified algorithmic patterns) within a request and applies 
    'Context Parameters' (business logic, variations) to generate specific 
    code variants (Variations).
    
    This approach mimics musical variations: maintaining the core logical 
    structure (the Theme) while adapting the surface-level details 
    (the Context) to fit new environments.

Author: AGI System Core
Version: 1.0.0
"""

import logging
import json
import re
from typing import Dict, Any, Optional, List, Callable
from dataclasses import dataclass, field
from datetime import datetime
from difflib import SequenceMatcher

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# --- Data Structures ---

@dataclass
class CodeTheme:
    """
    Represents a verified, reusable code template (The 'Theme').
    
    Attributes:
        id: Unique identifier for the theme.
        name: Human-readable name (e.g., 'CRUD Operations', 'Retry Pattern').
        pattern_signature: Keywords or regex patterns to identify this theme.
        template: The base code string with placeholders for context parameters.
        stability_score: A float (0.0-1.0) indicating the reliability of the code.
    """
    id: str
    name: str
    pattern_signature: List[str]
    template: str
    stability_score: float = 1.0
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

@dataclass
class VariationContext:
    """
    Represents the specific parameters for the business scenario (The 'Context').
    
    Attributes:
        params: A dictionary mapping template placeholders to actual values.
        constraints: Specific constraints (e.g., max_retries, specific library names).
    """
    params: Dict[str, Any]
    constraints: Dict[str, Any] = field(default_factory=dict)

class VariationalGeneratorError(Exception):
    """Base exception for the Variational Code Generator."""
    pass

class ThemeNotFoundError(VariationalGeneratorError):
    """Raised when no suitable theme is found for the given requirements."""
    pass

class TemplateRenderError(VariationalGeneratorError):
    """Raised when variable injection into the template fails."""
    pass

# --- Core Logic ---

class VariationalCodeGenerator:
    """
    The main engine for generating code variations based on high-stability themes.
    """
    
    def __init__(self):
        self.theme_library: Dict[str, CodeTheme] = {}
        self._initialize_default_themes()
        logger.info("Variational Code Generator initialized with %d themes.", len(self.theme_library))

    def _initialize_default_themes(self) -> None:
        """Pre-loads the library with fundamental, verified algorithmic patterns."""
        
        # Theme 1: Robust API Request Pattern (Retry Logic)
        retry_theme = CodeTheme(
            id="pattern_retry_mechanism_01",
            name="Robust API Request",
            pattern_signature=["request", "api", "retry", "network", "fetch"],
            template="""
import requests
import time
from typing import Optional, Dict, Any

def fetch_data_with_retry(url: str, max_retries: int = 3, delay: float = 1.0) -> Optional[Dict[str, Any]]:
    '''
    Fetches data from a URL with robust retry logic.
    Generated by Variational Code Generator.
    Context: {context_description}
    '''
    headers = {headers_def}
    
    for attempt in range(max_retries):
        try:
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt + 1} failed: {{e}}")
            if attempt < max_retries - 1:
                time.sleep(delay)
            else:
                return None
""",
            stability_score=0.98
        )
        
        # Theme 2: Batch Data Processing Pattern
        batch_theme = CodeTheme(
            id="pattern_batch_process_02",
            name="Batch Data Processor",
            pattern_signature=["batch", "process", "chunk", "large data", "transform"],
            template="""
from typing import List, Iterator, Any
import logging

logger = logging.getLogger(__name__)

def process_in_batches(data_stream: List[Any], batch_size: int = 100) -> Iterator[List[Any]]:
    '''
    Processes data in chunks to optimize memory usage.
    Transformation Logic: {transform_logic}
    '''
    total_items = len(data_stream)
    for i in range(0, total_items, batch_size):
        batch = data_stream[i:i + batch_size]
        # Apply transformation logic here
        processed_batch = [{transform_logic} for item in batch]
        yield processed_batch
""",
            stability_score=0.95
        )
        
        self.theme_library[retry_theme.id] = retry_theme
        self.theme_library[batch_theme.id] = batch_theme

    def _match_theme(self, requirement_keywords: List[str]) -> Optional[CodeTheme]:
        """
        [Helper Function]
        Identifies the best matching theme based on requirement keywords.
        
        Args:
            requirement_keywords: List of strings extracted from the user prompt.
            
        Returns:
            The best matching CodeTheme or None.
        """
        best_match: Optional[CodeTheme] = None
        highest_score = 0.0
        
        for theme in self.theme_library.values():
            # Calculate similarity score based on keyword overlap
            match_count = 0
            for sig in theme.pattern_signature:
                if any(self._fuzzy_match(sig, kw) > 0.7 for kw in requirement_keywords):
                    match_count += 1
            
            current_score = match_count / len(theme.pattern_signature) if theme.pattern_signature else 0
            
            # Prioritize stability if scores are close
            if current_score > highest_score or \
               (current_score == highest_score and (best_match and theme.stability_score > best_match.stability_score)):
                highest_score = current_score
                best_match = theme
                
        if highest_score > 0.5:
            return best_match
        return None

    def _fuzzy_match(self, str1: str, str2: str) -> float:
        """Calculates similarity ratio between two strings."""
        return SequenceMatcher(None, str1.lower(), str2.lower()).ratio()

    def _validate_context(self, theme: CodeTheme, context: VariationContext) -> bool:
        """
        Validates if the context provides enough data to fill the template's critical placeholders.
        """
        # Extract placeholders from template (simple heuristic: looking for {var} that aren't escaped)
        placeholders = set(re.findall(r'\{([a-zA-Z_][a-zA-Z0-9_]*)\}', theme.template))
        
        # Check if all required placeholders are in context params
        missing = []
        for p in placeholders:
            # We allow formatting args like {e} or {attempt + 1} to be ignored if not in params
            # but specific logic placeholders must be present.
            if p not in context.params and not p.isdigit() and len(p) > 2: 
                missing.append(p)
        
        if missing:
            logger.warning(f"Missing context parameters for theme {theme.name}: {missing}")
            return False
        return True

    def generate_variation(self, requirement: str, context: VariationContext) -> str:
        """
        [Core Function 1]
        Main entry point to generate code based on a requirement string and context.
        
        Args:
            requirement: A natural language description of the task.
            context: The VariationContext containing specific parameters.
            
        Returns:
            A string containing the generated Python code.
            
        Raises:
            ThemeNotFoundError: If no pattern matches the requirement.
            TemplateRenderError: If context injection fails.
        """
        logger.info(f"Analyzing requirement: {requirement[:50]}...")
        
        # 1. Extract Keywords (Simplified NLP)
        # In a real AGI, this would be an embedding vector comparison
        keywords = re.findall(r'\b\w+\b', requirement.lower())
        
        # 2. Identify Theme
        theme = self._match_theme(keywords)
        if not theme:
            logger.error("No verified theme found for the given requirement.")
            raise ThemeNotFoundError("Unable to map requirement to a verified code theme.")
            
        logger.info(f"Theme identified: {theme.name} (Stability: {theme.stability_score})")
        
        # 3. Validate Context
        if not self._validate_context(theme, context):
            raise TemplateRenderError("Insufficient context parameters for the selected theme.")
            
        # 4. Render Variation
        try:
            # We use safe_substitute or format_map logic.
            # Note: Standard str.format() fails if keys are missing or if there are formatting braces like {e}
            # We will manually inject for robustness
            
            code = theme.template
            for key, value in context.params.items():
                # Simple replacement for our specific template structure
                code = code.replace(f"{{{key}}}", str(value))
                
            # Add metadata header
            header = f"# Auto-generated Variation\n# Theme: {theme.name} (ID: {theme.id})\n# Generated at: {datetime.now().isoformat()}\n\n"
            
            return header + code

        except Exception as e:
            logger.error(f"Template rendering failed: {str(e)}")
            raise TemplateRenderError(f"Failed to render code variation: {str(e)}")

    def register_theme(self, theme: CodeTheme) -> bool:
        """
        [Core Function 2]
        Allows the AGI system to 'solidify' new patterns into the library.
        
        Args:
            theme: A CodeTheme object to add to the library.
            
        Returns:
            True if successful, False if ID exists.
        """
        if theme.id in self.theme_library:
            logger.warning(f"Attempted to register duplicate theme ID: {theme.id}")
            return False
        
        if not theme.pattern_signature or not theme.template:
            raise ValueError("Theme must contain signatures and template.")
            
        self.theme_library[theme.id] = theme
        logger.info(f"New theme registered: {theme.name}")
        return True

# --- Usage Example & Demonstration ---

def main():
    """
    Demonstrates the workflow of the Variational Code Generator.
    """
    print("--- Initializing System ---")
    generator = VariationalCodeGenerator()
    
    # Scenario 1: Generating an API client
    print("\n--- Scenario 1: Network Request ---")
    
    # User Requirement (The 'Melody')
    requirement_text = "I need to fetch user data from an external API with retry capabilities."
    
    # Context Parameters (The 'Orchestration')
    # We define specific headers and a custom context description
    api_context = VariationContext(
        params={
            "context_description": "Fetching user profile from internal auth service",
            "headers_def": "{'Authorization': 'Bearer TOKEN', 'Content-Type': 'application/json'}"
        }
    )
    
    try:
        generated_code = generator.generate_variation(requirement_text, api_context)
        print("Generated Code:\n")
        print(generated_code)
    except VariationalGeneratorError as e:
        print(f"Error: {e}")

    # Scenario 2: Data Processing
    print("\n--- Scenario 2: Data Transformation ---")
    
    batch_requirement = "Process a large list of transaction records in batches."
    
    batch_context = VariationContext(
        params={
            "transform_logic": "item.upper() if isinstance(item, str) else item",
            "context_description": "Normalizing transaction IDs"
        }
    )
    
    try:
        generated_code = generator.generate_variation(batch_requirement, batch_context)
        print("Generated Code:\n")
        print(generated_code)
    except VariationalGeneratorError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()