"""
Module: active_sampling_curiosity.py

This module implements an advanced active sampling strategy for Human-Computer Symbiosis (HCS).
In an AGI system, the space of generated hypotheses is vast, while human verification bandwidth
is scarce. This module provides a 'Curiosity Algorithm' that selects hypotheses based on
maximizing information entropy and uncertainty reduction.

The core strategy involves:
1. Estimating the uncertainty (entropy) of unverified hypotheses.
2. Simulating the impact of human verification on the system's global uncertainty.
3. Selecting the hypothesis that yields the highest Information Gain per Human Interaction Cost.

Author: Senior Python Engineer (AGI Division)
Version: 1.0.0
"""

import logging
import math
import random
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

# Configure structured logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("ActiveSamplingCuriosity")


class HypothesisValidationError(Exception):
    """Custom exception for invalid hypothesis data."""
    pass


@dataclass
class Hypothesis:
    """
    Represents a single hypothesis generated by the AGI system.
    
    Attributes:
        id: Unique identifier for the hypothesis.
        description: Text description of the hypothesis.
        probability: Current belief probability (0.0 to 1.0) that the hypothesis is true.
        dependency_ids: List of other hypothesis IDs that this hypothesis depends on.
        verification_cost: Estimated human effort required to verify (1.0 = standard effort).
    """
    id: str
    description: str
    probability: float = 0.5
    dependency_ids: List[str] = field(default_factory=list)
    verification_cost: float = 1.0

    def __post_init__(self):
        """Validate data after initialization."""
        if not 0.0 <= self.probability <= 1.0:
            raise HypothesisValidationError(f"Probability {self.probability} out of bounds [0, 1] for {self.id}")
        if self.verification_cost <= 0:
            raise HypothesisValidationError("Verification cost must be positive.")


def calculate_shannon_entropy(probability: float) -> float:
    """
    Calculate the Shannon entropy (uncertainty) of a binary event.
    
    H(p) = -p*log2(p) - (1-p)*log2(1-p)
    
    Args:
        probability: The probability of the event occurring.
        
    Returns:
        The entropy value in bits. Returns 0 if probability is 0 or 1.
    """
    try:
        if probability <= 0.0 or probability >= 1.0:
            return 0.0
        return - (probability * math.log2(probability) + 
                  (1 - probability) * math.log2(1 - probability))
    except (ValueError, ZeroDivisionError) as e:
        logger.error(f"Entropy calculation error for p={probability}: {e}")
        return 0.0


class CuriositySampler:
    """
    Core class for Active Sampling.
    
    Implements strategies to filter massive hypothesis sets into a prioritized
    'To-Verify' list for human partners, aiming to minimize system entropy
    with minimal human effort.
    """

    def __init__(self, hypotheses: List[Hypothesis]):
        """
        Initialize the sampler with a list of hypotheses.
        
        Args:
            hypotheses: List of Hypothesis objects to sample from.
        """
        self.hypotheses = {h.id: h for h in hypotheses}
        logger.info(f"CuriositySampler initialized with {len(self.hypotheses)} hypotheses.")

    def _get_total_system_entropy(self) -> float:
        """
        Helper function to calculate the current total entropy of the system.
        """
        return sum(calculate_shannon_entropy(h.probability) for h in self.hypotheses.values())

    def rank_by_uncertainty(self, top_k: int = 10) -> List[Tuple[str, float]]:
        """
        Rank hypotheses purely by their current uncertainty (Entropy).
        High entropy = High uncertainty = High potential for learning.
        
        Args:
            top_k: Number of top candidates to return.
            
        Returns:
            List of tuples (hypothesis_id, entropy_score).
        """
        if top_k <= 0:
            raise ValueError("top_k must be a positive integer")

        scored_hypotheses = []
        for h in self.hypotheses.values():
            entropy = calculate_shannon_entropy(h.probability)
            scored_hypotheses.append((h.id, entropy))
        
        # Sort by entropy descending
        scored_hypotheses.sort(key=lambda x: x[1], reverse=True)
        
        logger.debug(f"Ranked {len(scored_hypotheses)} hypotheses by uncertainty.")
        return scored_hypotheses[:top_k]

    def select_optimal_verification_task(self) -> Optional[Hypothesis]:
        """
        Select the single best hypothesis for human verification based on
        Expected Information Gain (EIG) normalized by Cost.
        
        Strategy:
        1. Simulate verifying hypothesis H.
        2. If H is True (p), system entropy reduces by H's entropy.
        3. If H is False (1-p), system entropy reduces by H's entropy.
        4. Expected Gain = Entropy of H.
        5. Efficiency = Expected Gain / Cost.
        
        Returns:
            The optimal Hypothesis object to verify, or None if system is stable.
        """
        best_candidate: Optional[Hypothesis] = None
        max_efficiency: float = -1.0

        for h in self.hypotheses.values():
            # Information gain is essentially the removal of uncertainty about this hypothesis
            current_entropy = calculate_shannon_entropy(h.probability)
            
            if current_entropy < 1e-4:
                continue # Skip already certain hypotheses

            # Normalize by cost
            efficiency = current_entropy / h.verification_cost
            
            # Check dependencies (Simple heuristic: if dependencies are uncertain, 
            # verifying this might be less effective until deps are resolved)
            # For this implementation, we keep it simple but log dependency complexity.
            if h.dependency_ids:
                dep_entropy = sum(
                    calculate_shannon_entropy(self.hypotheses[dep_id].probability) 
                    for dep_id in h.dependency_ids if dep_id in self.hypotheses
                )
                # Heuristic penalty: if parent nodes are chaotic, weigh this node slightly less
                # to prevent chasing down rabbit holes
                penalty = 1.0 / (1.0 + math.sqrt(dep_entropy))
                efficiency *= penalty

            if efficiency > max_efficiency:
                max_efficiency = efficiency
                best_candidate = h

        if best_candidate:
            logger.info(f"Selected optimal task: {best_candidate.id} "
                        f"(Entropy: {calculate_shannon_entropy(best_candidate.probability):.4f}, "
                        f"Cost: {best_candidate.verification_cost}, "
                        f"Efficiency: {max_efficiency:.4f})")
        else:
            logger.info("No optimal task found. System might be in a low-entropy state.")
            
        return best_candidate


# --- Usage Example ---
if __name__ == "__main__":
    # Seed for reproducibility
    random.seed(42)
    
    # 1. Generate synthetic AGI hypothesis space
    print("--- Generating Synthetic Hypothesis Space ---")
    raw_hypotheses = []
    for i in range(100):
        # Create probabilities clustered around 0.5 (uncertain) and edges (certain)
        # to simulate a realistic distribution
        if random.random() > 0.8:
            prob = random.uniform(0.45, 0.55) # High uncertainty
        else:
            prob = random.uniform(0.0, 1.0) # Random
            
        raw_hypotheses.append(
            Hypothesis(
                id=f"HYPO_{i:03d}",
                description=f"Automated conjecture number {i}",
                probability=prob,
                verification_cost=random.uniform(0.5, 2.0),
                dependency_ids=[f"HYPO_{(i-1):03d}"] if i > 0 and random.random() > 0.7 else []
            )
        )

    # 2. Initialize Sampler
    sampler = CuriositySampler(raw_hypotheses)

    # 3. Strategy A: Pure Uncertainty Ranking
    print("\n--- Top 5 Uncertain Hypotheses ---")
    top_uncertain = sampler.rank_by_uncertainty(top_k=5)
    for hid, score in top_uncertain:
        print(f"ID: {hid}, Entropy: {score:.4f}")

    # 4. Strategy B: Optimal Task Selection (Cost-Aware)
    print("\n--- Optimal Task for Human (Cost-Adjusted) ---")
    task = sampler.select_optimal_verification_task()
    if task:
        print(f"Recommended Action: Verify '{task.id}'")
        print(f"   Description: {task.description}")
        print(f"   Current Probability: {task.probability:.4f}")
        print(f"   Estimated Cost: {task.verification_cost}")