"""
Module: auto_concept_collapse_detector.py
Description: Implements 'Concept Collapse & Overfitting Detection' in Bottom-Up Inductive Construction.
             It validates newly induced nodes by comparing their Kolmogorov complexity (approximate)
             against the Information Content of the phenomena they explain.
Author: AGI System
Version: 1.0.0
"""

import logging
import math
from dataclasses import dataclass
from typing import List, Optional, Dict, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("ConceptCollapseDetector")


@dataclass
class Phenomenon:
    """
    Represents an observable data point or phenomenon in the environment.
    
    Attributes:
        id (str): Unique identifier for the phenomenon.
        data (bytes): The raw data of the phenomenon.
        occurrences (int): Number of times this specific phenomenon has been observed.
    """
    id: str
    data: bytes
    occurrences: int = 1

    def __post_init__(self):
        if not isinstance(self.data, bytes):
            raise ValueError("Phenomenon data must be in bytes format.")
        if self.occurrences < 1:
            raise ValueError("Occurrences must be at least 1.")


@dataclass
class InductiveNode:
    """
    Represents a candidate concept/abstraction generated by the system.
    
    Attributes:
        id (str): Unique identifier for the concept node.
        definition (bytes): The 'code' or 'rule' defining the node (e.g., a compressed pattern).
        covered_phenomena (List[Phenomenon]): The list of observed phenomena this node explains.
        complexity_penalty (float): A constant added to complexity to account for computational overhead.
    """
    id: str
    definition: bytes
    covered_phenomena: List[Phenomena]  # type: ignore
    complexity_penalty: float = 10.0  # Default penalty to prevent trivial matches

    def __post_init__(self):
        if not self.covered_phenomena:
            raise ValueError("InductiveNode must cover at least one phenomenon.")


def calculate_shannon_entropy(data: bytes) -> float:
    """
    Calculate the Shannon Entropy (Information Content) of a byte sequence.
    This serves as a proxy for the information density of the raw data.

    Args:
        data (bytes): Input byte sequence.

    Returns:
        float: Entropy in bits.
    """
    if not data:
        return 0.0

    frequency: Dict[int, int] = {}
    for byte in data:
        frequency[byte] = frequency.get(byte, 0) + 1
    
    length = len(data)
    entropy = 0.0
    
    for count in frequency.values():
        probability = count / length
        if probability > 0:
            entropy -= probability * math.log2(probability)
            
    return entropy


def calculate_compression_metrics(node: InductiveNode) -> Dict[str, float]:
    """
    Core Function 1.
    Calculates the Information Compression metrics for a specific Inductive Node.
    
    It compares the complexity of the Node's Definition (the 'Theory') vs.
    the Information Content of the Phenomena it explains (the 'Evidence').

    Args:
        node (InductiveNode): The candidate node to evaluate.

    Returns:
        Dict[str, float]: A dictionary containing:
            - 'theory_complexity': Estimated bits required to store the definition.
            - 'evidence_volume': Total bits of information the theory explains.
            - 'compression_ratio': Evidence / Theory (Higher is better).
            - 'net_gain': Evidence - Theory (Must be positive for valid compression).
    """
    logger.info(f"Calculating compression metrics for Node ID: {node.id}")

    # 1. Estimate Theory Complexity (Description Length)
    # We approximate the complexity of the concept by the entropy of its definition bytes.
    # In a real AGI system, this might be the MDL (Minimum Description Length) of the generative model.
    theory_entropy = calculate_shannon_entropy(node.definition)
    # Total complexity = Entropy per byte * Size + Overhead Penalty
    theory_complexity = (theory_entropy * len(node.definition)) + node.complexity_penalty

    # 2. Calculate Evidence Volume (Information Explained)
    # Sum of (Information of one instance * Frequency)
    total_evidence_bits = 0.0
    
    for p in node.covered_phenomena:
        # If the theory explains a phenomenon, it effectively 'compresses' it.
        # We measure the raw information content of the phenomenon.
        phen_entropy = calculate_shannon_entropy(p.data)
        phen_bits = phen_entropy * len(p.data)
        
        # We weight by occurrences. Explaining a frequent pattern is more valuable.
        total_evidence_bits += (phen_bits * p.occurrences)

    # 3. Validate and Calculate Ratios
    if theory_complexity <= 0:
        logger.warning(f"Node {node.id} has zero or negative complexity.")
        theory_complexity = 1e-6  # Prevent division by zero

    compression_ratio = total_evidence_bits / theory_complexity
    net_gain = total_evidence_bits - theory_complexity

    return {
        "theory_complexity": theory_complexity,
        "evidence_volume": total_evidence_bits,
        "compression_ratio": compression_ratio,
        "net_gain": net_gain
    }


def detect_overfitting(node: InductiveNode, ratio_threshold: float = 1.5) -> bool:
    """
    Core Function 2.
    Determines if an Inductive Node is valid or 'Collapsed/Overfitted'.
    
    Overfitting occurs when the theory (Node) is more complex than the 
    patterns it explains (low compression ratio), or when it merely memorizes 
    noise (net gain is negative or marginal).

    Args:
        node (InductiveNode): The candidate node to validate.
        ratio_threshold (float): The minimum acceptable compression ratio. 
                                 Default 1.5 implies the theory must explain 
                                 1.5x its own complexity worth of data.

    Returns:
        bool: True if the node is VALID (passes check), False if OVERFITTED (fails check).
    """
    logger.info(f"Detecting overfitting for Node ID: {node.id} with threshold {ratio_threshold}")

    try:
        metrics = calculate_compression_metrics(node)
        
        net_gain = metrics['net_gain']
        ratio = metrics['compression_ratio']

        logger.debug(f"Metrics - Net Gain: {net_gain:.2f}, Ratio: {ratio:.2f}")

        # Validation Logic
        if net_gain < 0:
            logger.warning(f"Node {node.id} rejected: Negative Net Gain ({net_gain:.2f}). The theory is more complex than the data it explains.")
            return False
        
        if ratio < ratio_threshold:
            logger.warning(f"Node {node.id} rejected: Low Compression Ratio ({ratio:.2f} < {ratio_threshold}). Likely noise or weak pattern.")
            return False

        logger.info(f"Node {node.id} validated successfully. Compression Ratio: {ratio:.2f}")
        return True

    except ZeroDivisionError:
        logger.error("Division by zero encountered during detection.")
        return False
    except Exception as e:
        logger.error(f"Unexpected error during overfitting detection: {e}")
        return False


def summarize_validation(node: InductiveNode, is_valid: bool) -> str:
    """
    Helper Function.
    Generates a human-readable summary of the validation result.

    Args:
        node (InductiveNode): The node evaluated.
        is_valid (bool): The result of the validation.

    Returns:
        str: A summary string.
    """
    metrics = calculate_compression_metrics(node)
    status = "VALID (Generalizable)" if is_valid else "INVALID (Overfitted/Collapsed)"
    
    return (
        f"Validation Report for [{node.id}]:\n"
        f"  Status: {status}\n"
        f"  Theory Complexity: {metrics['theory_complexity']:.2f} bits\n"
        f"  Explained Evidence: {metrics['evidence_volume']:.2f} bits\n"
        f"  Net Information Gain: {metrics['net_gain']:.2f}\n"
        f"  Compression Ratio: {metrics['compression_ratio']:.2f}x"
    )

# --- Usage Example ---

if __name__ == "__main__":
    # Example 1: A valid pattern (Repeated Sequence)
    # The definition is small, but it explains a large amount of repeated data.
    pattern_data = b"abcdefgh" * 10  # 80 bytes
    simple_definition = b"repeat('abcdefgh', 10)"  # Small definition
    
    # Create phenomena that this node explains
    # We observe the sequence 'abcdefgh' multiple times
    observed_phenomena = [
        Phenomenon(id="obs_1", data=pattern_data, occurrences=5), # Seen 5 times
        Phenomenon(id="obs_2", data=pattern_data, occurrences=2)  # Seen 2 times
    ]

    valid_node = InductiveNode(
        id="concept_sequence_abc",
        definition=simple_definition,
        covered_phenomena=observed_phenomena,
        complexity_penalty=20.0 # Arbitrary penalty for the 'concept' overhead
    )

    print("-" * 60)
    is_valid = detect_overfitting(valid_node, ratio_threshold=1.5)
    print(summarize_validation(valid_node, is_valid))

    # Example 2: Overfitting (Noise as Rule)
    # We try to create a rule for random data. The definition must contain the data itself.
    random_data = b"\x13\x37\xbe\xef\xca\xfe" # Random bytes
    # To 'explain' this, the definition is basically the data itself (plus overhead)
    complex_definition = b"store_raw(" + random_data + b")"
    
    noise_phenomena = [
        Phenomenon(id="noise_1", data=random_data, occurrences=1) # Only seen once
    ]

    overfitted_node = InductiveNode(
        id="concept_random_blob",
        definition=complex_definition,
        covered_phenomena=noise_phenomena,
        complexity_penalty=10.0
    )

    print("-" * 60)
    is_valid_noise = detect_overfitting(overfitted_node, ratio_threshold=1.5)
    print(summarize_validation(overfitted_node, is_valid_noise))
    print("-" * 60)