"""
Module: implicit_feedback_mining.py

This module is designed for AGI systems to mine implicit negative feedback from
human-AI interaction logs. It quantifies the extent of human modifications on
AI-generated content (the "Human-in-the-Loop" practice) using text difference
algorithms.

The core hypothesis is that a significant divergence between the AI's output
and the human's final version indicates a quality issue with the original node
or a failure in the model's generalization capability.

Author: AGI System Core Engineer
Version: 1.0.0
"""

import difflib
import logging
import math
from dataclasses import dataclass
from typing import List, Tuple, Optional, Dict, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@dataclass
class FeedbackAnalysisResult:
    """
    Data structure to hold the result of the implicit feedback analysis.
    
    Attributes:
        similarity_score (float): Normalized similarity between 0.0 and 1.0.
        edit_distance (int): The Levenshtein distance equivalent (approx).
        modification_ratio (float): Ratio of modified characters to total length.
        is_negative_feedback (bool): True if modification exceeds threshold.
        diff_details (List[str]): Detailed diff operations (optional).
    """
    similarity_score: float
    edit_distance: int
    modification_ratio: float
    is_negative_feedback: bool
    diff_details: Optional[List[str]] = None


def _preprocess_text(text: str, case_sensitive: bool = False) -> str:
    """
    Helper function to sanitize and prepare text for comparison.
    
    Strips leading/trailing whitespace and optionally lowers case.
    
    Args:
        text (str): The raw input text.
        case_sensitive (bool): Whether comparison should be case-sensitive.
        
    Returns:
        str: The processed text.
    """
    if not isinstance(text, str):
        logger.warning(f"Invalid input type for preprocessing: {type(text)}. Casting to string.")
        text = str(text)
    
    processed = text.strip()
    if not case_sensitive:
        processed = processed.lower()
    return processed


def calculate_modification_metrics(
    ai_content: str, 
    human_content: str, 
    case_sensitive: bool = False
) -> Tuple[float, int, float]:
    """
    Calculate core metrics comparing AI output to Human modification.
    
    Uses SequenceMatcher from difflib to find the longest contiguous matching
    blocks to determine similarity.
    
    Args:
        ai_content (str): The original content generated by the AI.
        human_content (str): The content after human modification.
        case_sensitive (bool): Flag to consider case sensitivity.
        
    Returns:
        Tuple[float, int, float]: 
            - similarity_ratio (0.0 to 1.0)
            - approximate_edit_distance (int)
            - modification_intensity (0.0 to 1.0+)
            
    Raises:
        ValueError: If inputs cannot be processed.
    """
    logger.debug("Starting metric calculation.")
    
    # Input validation
    if ai_content is None or human_content is None:
        logger.error("Input content cannot be None.")
        raise ValueError("Input content cannot be None.")

    s1 = _preprocess_text(ai_content, case_sensitive)
    s2 = _preprocess_text(human_content, case_sensitive)
    
    # Edge case: Both empty
    if not s1 and not s2:
        return 1.0, 0, 0.0
    
    # Initialize SequenceMatcher
    matcher = difflib.SequenceMatcher(None, s1, s2)
    similarity_ratio = matcher.ratio()
    
    # Calculate approximate edit distance operations
    # opcodes returns tags: 'replace', 'delete', 'insert', 'equal'
    # We sum the lengths of non-equal blocks
    opcodes = matcher.get_opcodes()
    edit_distance = 0
    
    for tag, i1, i2, j1, j2 in opcodes:
        if tag != 'equal':
            # Simple approximation of edit cost
            edit_distance += max(i2 - i1, j2 - j1)
            
    # Calculate modification intensity relative to original length
    # Avoid division by zero
    len_original = len(s1)
    if len_original == 0:
        # If AI said nothing and Human added things, it's 100% modification (or undefined)
        mod_intensity = 1.0 if len(s2) > 0 else 0.0
    else:
        mod_intensity = edit_distance / len_original

    logger.debug(f"Metrics: Sim={similarity_ratio:.3f}, Dist={edit_distance}, Intensity={mod_intensity:.3f}")
    
    return similarity_ratio, edit_distance, mod_intensity


def analyze_implicit_feedback(
    node_id: str,
    ai_output: str,
    human_final_version: str,
    threshold: float = 0.75,
    return_diff: bool = True
) -> FeedbackAnalysisResult:
    """
    Main function to analyze a specific interaction node for implicit feedback.
    
    Determines if the human modification constitutes a negative feedback signal
    based on the divergence threshold.
    
    Args:
        node_id (str): Identifier for the workflow node.
        ai_output (str): The raw text generated by the model.
        human_final_version (str): The text after the user edited it.
        threshold (float): The similarity score below which feedback is considered 
                           negative (indicating poor quality). Default 0.75.
        return_diff (bool): Whether to include the detailed diff in the result.
        
    Returns:
        FeedbackAnalysisResult: A structured object containing analysis results.
        
    Example:
        >>> ai_text = "The capital of France is London."
        >>> human_text = "The capital of France is Paris."
        >>> result = analyze_implicit_feedback("node_123", ai_text, human_text)
        >>> print(result.is_negative_feedback)
        True
    """
    logger.info(f"Analyzing implicit feedback for node: {node_id}")
    
    # Data Validation
    if not isinstance(threshold, (int, float)) or not (0.0 <= threshold <= 1.0):
        logger.warning(f"Invalid threshold {threshold}, resetting to default 0.75")
        threshold = 0.75

    try:
        similarity, dist, intensity = calculate_modification_metrics(ai_output, human_final_version)
    except ValueError as e:
        logger.error(f"Calculation failed for node {node_id}: {e}")
        # Return a high-penalty result on failure
        return FeedbackAnalysisResult(
            similarity_score=0.0,
            edit_distance=9999,
            modification_ratio=1.0,
            is_negative_feedback=True
        )

    # Determine if the modification counts as negative feedback
    # Low similarity = High modification = Negative Feedback
    is_negative = similarity < threshold
    
    if is_negative:
        logger.warning(
            f"Node {node_id} flagged as IMPLICIT NEGATIVE FEEDBACK. "
            f"Similarity: {similarity:.2f} < Threshold: {threshold}"
        )
    
    # Generate detailed diff if requested
    diff_ops = None
    if return_diff:
        s1 = _preprocess_text(ai_output)
        s2 = _preprocess_text(human_final_version)
        # Using unified_diff format for readability
        diff_ops = list(difflib.unified_diff(
            s1.splitlines(keepends=True), 
            s2.splitlines(keepends=True),
            fromfile="ai_output", 
            tofile="human_edit"
        ))

    return FeedbackAnalysisResult(
        similarity_score=similarity,
        edit_distance=dist,
        modification_ratio=intensity,
        is_negative_feedback=is_negative,
        diff_details=diff_ops
    )


def batch_process_interaction_logs(
    interaction_logs: List[Dict[str, Any]], 
    global_threshold: float = 0.75
) -> Dict[str, Any]:
    """
    Processes a batch of interaction logs to aggregate quality signals.
    
    This function simulates the input of an AGI training pipeline.
    
    Args:
        interaction_logs (List[Dict]): List of dictionaries containing 
                                       'node_id', 'ai_text', 'human_text'.
        global_threshold (float): Similarity threshold.
        
    Returns:
        Dict[str, Any]: Summary statistics including low quality node IDs.
        
    Input Format Example:
        [
            {"node_id": "1", "ai_text": "Hello", "human_text": "Hi"},
            {"node_id": "2", "ai_text": "Sky is green", "human_text": "Sky is blue"}
        ]
    """
    logger.info(f"Starting batch processing for {len(interaction_logs)} logs.")
    
    if not interaction_logs:
        return {"status": "empty", "low_quality_nodes": []}
    
    results = []
    low_quality_nodes = []
    total_similarity = 0.0
    
    for log in interaction_logs:
        # Boundary check for keys
        if not all(k in log for k in ['node_id', 'ai_text', 'human_text']):
            logger.warning(f"Skipping malformed log entry: {log}")
            continue
            
        res = analyze_implicit_feedback(
            node_id=log['node_id'],
            ai_output=log['ai_text'],
            human_final_version=log['human_text'],
            threshold=global_threshold,
            return_diff=False # Disable diff for batch processing to save memory
        )
        
        results.append(res)
        total_similarity += res.similarity_score
        
        if res.is_negative_feedback:
            low_quality_nodes.append(log['node_id'])
            
    avg_similarity = total_similarity / len(results) if results else 0.0
    
    return {
        "total_logs_processed": len(results),
        "average_similarity": avg_similarity,
        "detected_low_quality_count": len(low_quality_nodes),
        "low_quality_node_ids": low_quality_nodes,
        "quality_score": 1.0 - (len(low_quality_nodes) / len(results)) if results else 0.0
    }


if __name__ == "__main__":
    # Usage Example
    sample_ai_output = """
    def calculate_sum(a, b):
        return a - b
    """
    
    sample_human_fix = """
    def calculate_sum(a, b):
        # Fixed the logic error
        return a + b
    """
    
    print("--- Running Single Analysis Example ---")
    result = analyze_implicit_feedback(
        node_id="code_gen_001",
        ai_output=sample_ai_output,
        human_final_version=sample_human_fix,
        threshold=0.9 # High standard for code
    )
    
    print(f"Node ID: code_gen_001")
    print(f"Similarity Score: {result.similarity_score:.4f}")
    print(f"Is Negative Feedback: {result.is_negative_feedback}")
    
    if result.diff_details:
        print("\n--- Detected Changes (Diff) ---")
        print("".join(result.diff_details))

    print("\n--- Running Batch Analysis Example ---")
    batch_data = [
        {"node_id": "t_01", "ai_text": "Color is Red", "human_text": "Colour is Red"}, # Minor
        {"node_id": "t_02", "ai_text": "Gravity pushes up", "human_text": "Gravity pulls down"}, # Major
        {"node_id": "t_03", "ai_text": "E = mc^2", "human_text": "E = mc^2"} # Perfect
    ]
    
    batch_report = batch_process_interaction_logs(batch_data, global_threshold=0.8)
    print(f"Batch Quality Score: {batch_report['quality_score']:.2f}")
    print(f"Low Quality Nodes: {batch_report['low_quality_node_ids']}")