"""
Module: auto_cross_domain_conflict_arbitration
Description: Implements a 'Cross-Domain Conflict Arbitration' mechanism.
             This module resolves conflicts between 'Economic Rationality' (profit maximization)
             and 'Social Ethics' (non-deception) by introducing a 'Legal/Moral' meta-node.
             If arbitration fails, it enforces the 'Minimum Harm Principle' and halts actions
             pending human intervention.

Author: AGI System Core Engineer
Version: 1.0.0
License: MIT
"""

import logging
from enum import Enum, auto
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("CrossDomainArbitrator")


class DomainType(Enum):
    """Enumeration of the cognitive domains involved in decision making."""
    ECONOMIC_RATIONALITY = auto()
    SOCIAL_ETHICS = auto()
    LEGAL_MORAL = auto()  # The Meta-Node


class DecisionOutcome(Enum):
    """Enumeration of possible arbitration outcomes."""
    ALLOW = auto()          # Action is approved
    DENY = auto()           # Action is rejected
    ESCALATE = auto()       # Cannot resolve, requires human intervention


@dataclass
class ActionProposal:
    """Represents a proposed action generated by the AGI system.
    
    Attributes:
        action_id: Unique identifier for the action.
        description: Human-readable description of the action.
        domain_scores: A dictionary mapping DomainType to a relevance score (0.0 to 1.0).
                       Higher score indicates stronger alignment or conflict intensity.
        raw_content: Optional dictionary containing raw data for the action.
    """
    action_id: str
    description: str
    domain_scores: Dict[DomainType, float] = field(default_factory=dict)
    raw_content: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        """Validate data after initialization."""
        if not self.action_id:
            raise ValueError("Action ID cannot be empty.")
        
        for domain, score in self.domain_scores.items():
            if not (0.0 <= score <= 1.0):
                raise ValueError(f"Score for {domain.name} must be between 0.0 and 1.0.")


@dataclass
class ArbitrationResult:
    """Contains the result of the arbitration process.
    
    Attributes:
        action_id: The ID of the judged action.
        outcome: The final DecisionOutcome.
        reasoning: Explanation for the decision.
        requires_human_intervention: Boolean flag indicating if the system should pause.
    """
    action_id: str
    outcome: DecisionOutcome
    reasoning: str
    requires_human_intervention: bool = False


class ConflictArbitrationError(Exception):
    """Custom exception for errors during the arbitration process."""
    pass


def _calculate_conflict_intensity(
    scores: Dict[DomainType, float], 
    domain_a: DomainType, 
    domain_b: DomainType
) -> float:
    """
    Helper function to calculate the intensity of conflict between two domains.
    
    A simple heuristic: if both domains have high scores, the conflict is intense.
    
    Args:
        scores: The dictionary of domain scores.
        domain_a: First domain.
        domain_b: Second domain.
        
    Returns:
        A float representing conflict intensity (0.0 to 1.0).
    """
    score_a = scores.get(domain_a, 0.0)
    score_b = scores.get(domain_b, 0.0)
    
    # If both are highly relevant (e.g., High Profit AND High Ethical violation), conflict is max.
    # Logic: Product of probabilities or minimum overlap.
    return min(score_a, score_b)


def evaluate_legal_moral_meta_node(proposal: ActionProposal) -> Tuple[DecisionOutcome, str]:
    """
    [Core Function 1]
    Simulates the 'Legal/Moral' meta-node judgment.
    
    In a real AGI system, this would query a knowledge graph of laws and moral philosophy.
    Here, we simulate specific scenario handling (e.g., deceptive marketing).
    
    Args:
        proposal: The action proposal to evaluate.
        
    Returns:
        A tuple of (DecisionOutcome, reasoning_string).
        
    Raises:
        ConflictArbitrationError: If input data is malformed.
    """
    if not proposal.domain_scores:
        raise ConflictArbitrationError("Proposal lacks domain scores for evaluation.")

    logger.info(f"Evaluating Proposal {proposal.action_id} via Legal/Moral Meta-Node...")

    # Scenario Simulation: "Exaggerated Marketing"
    # High Economic Score (Profit) + High Social Ethics Score (Violation of Non-Deception)
    has_profit_motive = proposal.domain_scores.get(DomainType.ECONOMIC_RATIONALITY, 0) > 0.7
    has_ethical_violation = proposal.domain_scores.get(DomainType.SOCIAL_ETHICS, 0) > 0.6

    if has_profit_motive and has_ethical_violation:
        # Specific rule: Deception for profit is generally illegal/unethical
        if "decept" in proposal.description.lower() or "exaggerat" in proposal.description.lower():
            return (
                DecisionOutcome.DENY, 
                "Violation of Consumer Protection Laws: Deceptive trade practices detected."
            )
        
        # Ambiguous case: Profit motive exists, ethical concern exists, but not explicitly illegal
        return (
            DecisionOutcome.ESCALATE, 
            "Potential ethical gray area detected. Logic insufficient for autonomous execution."
        )

    # Default case: No high-intensity conflict found
    return (
        DecisionOutcome.ALLOW, 
        "Action complies with general moral and legal standards."
    )


def enforce_minimum_harm_principle(proposal: ActionProposal) -> ArbitrationResult:
    """
    [Core Function 2]
    The main arbitration orchestrator. 
    
    This function detects conflicts between Economic Rationality and Social Ethics.
    If a conflict exists, it calls the meta-node. If the meta-node returns ESCALATE,
    this function enforces the 'Minimum Harm Principle' (force pause).
    
    Args:
        proposal: The action proposal containing domain scores.
        
    Returns:
        An ArbitrationResult object with the final decision.
    """
    logger.info(f"Starting arbitration for Action: {proposal.action_id}")

    # 1. Detect Conflict Existence
    conflict_intensity = _calculate_conflict_intensity(
        proposal.domain_scores,
        DomainType.ECONOMIC_RATIONALITY,
        DomainType.SOCIAL_ETHICS
    )

    # Threshold for triggering arbitration
    if conflict_intensity < 0.3:
        logger.debug("Conflict intensity below threshold. No arbitration needed.")
        return ArbitrationResult(
            action_id=proposal.action_id,
            outcome=DecisionOutcome.ALLOW,
            reasoning="No significant cross-domain conflict detected.",
            requires_human_intervention=False
        )

    logger.warning(f"Cross-domain conflict detected! Intensity: {conflict_intensity:.2f}")

    # 2. Invoke Meta-Node for Judgment
    try:
        outcome, reasoning = evaluate_legal_moral_meta_node(proposal)
    except ConflictArbitrationError as e:
        logger.error(f"Arbitration logic failed: {e}")
        # Fallback to safety
        outcome = DecisionOutcome.ESCALATE
        reasoning = "Internal error during arbitration."

    # 3. Handle Escalation / Minimum Harm Principle
    if outcome == DecisionOutcome.ESCALATE:
        logger.critical("ARBITRATION FAILED. ENFORCING MINIMUM HARM PRINCIPLE.")
        logger.critical("System Action Paused. Awaiting Human Intervention.")
        
        return ArbitrationResult(
            action_id=proposal.action_id,
            outcome=DecisionOutcome.DENY, # Treat escalation as a denial of autonomous action
            reasoning=f"MINIMUM HARM PRINCIPLE APPLIED: {reasoning}",
            requires_human_intervention=True
        )

    # 4. Return Final Verdict
    return ArbitrationResult(
        action_id=proposal.action_id,
        outcome=outcome,
        reasoning=reasoning,
        requires_human_intervention=False
    )

# --- Usage Example ---
if __name__ == "__main__":
    # Example 1: Ethical Conflict (Exaggerated Marketing)
    marketing_proposal = ActionProposal(
        action_id="ACT-001",
        description="Launch marketing campaign with exaggerated battery life claims.",
        domain_scores={
            DomainType.ECONOMIC_RATIONALITY: 0.9,  # High profit potential
            DomainType.SOCIAL_ETHICS: 0.8         # High deception level
        }
    )

    # Example 2: Benign Action
    update_proposal = ActionProposal(
        action_id="ACT-002",
        description="Update server security patches.",
        domain_scores={
            DomainType.ECONOMIC_RATIONALITY: 0.2,  # Cost involved
            DomainType.SOCIAL_ETHICS: 0.1          # Low ethical relevance
        }
    )

    print("-" * 50)
    print(f"Processing: {marketing_proposal.description}")
    result_1 = enforce_minimum_harm_principle(marketing_proposal)
    print(f"Outcome: {result_1.outcome.name}")
    print(f"Reasoning: {result_1.reasoning}")
    print(f"Human Intervention Required: {result_1.requires_human_intervention}")
    print("-" * 50)

    print(f"Processing: {update_proposal.description}")
    result_2 = enforce_minimum_harm_principle(update_proposal)
    print(f"Outcome: {result_2.outcome.name}")
    print(f"Reasoning: {result_2.reasoning}")
    print("-" * 50)