"""
Neuro-Symbolic Intermediate Reasoning Layer (NS-IRL)

This module implements an intermediate reasoning layer that transforms a Large Language Model's (LLM)
reasoning process into a sequence of executable, symbolic primitives (e.g., [DECOMPOSE], [LOOKUP]).
This approach treats the LLM's output as "Neuro-Symbolic IR" rather than final text, enabling
explainable, interruptible, and verifiable reasoning chains.

Author: Auto-Generated AGI Skill
Version: 1.0.0
"""

import logging
import re
import json
from typing import List, Dict, Optional, Union, Any, Callable
from dataclasses import dataclass, field
from enum import Enum

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# --- Enums and Data Structures ---

class PrimitiveType(Enum):
    """Defines the types of reasoning primitives available in the IR."""
    DECOMPOSE = "DECOMPOSE"     # Break down a complex problem
    LOOKUP = "LOOKUP"           # Retrieve external knowledge
    COMPUTE = "COMPUTE"         # Perform mathematical/logical operations
    VERIFY = "VERIFY"           # Check consistency or facts
    SYNTHESIZE = "SYNTHESIZE"   # Aggregate results into a conclusion
    UNKNOWN = "UNKNOWN"         # Fallback for unrecognized tokens

@dataclass
class ReasoningStep:
    """Represents a single step in the reasoning chain."""
    step_id: int
    primitive: PrimitiveType
    content: str
    args: Dict[str, Any] = field(default_factory=dict)
    result: Optional[str] = None
    is_verified: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serializes the step to a dictionary."""
        return {
            "step_id": self.step_id,
            "primitive": self.primitive.value,
            "content": self.content,
            "args": self.args,
            "result": self.result,
            "is_verified": self.is_verified
        }

# --- Custom Exceptions ---

class ReasoningError(Exception):
    """Base exception for reasoning layer errors."""
    pass

class PrimitiveExecutionError(ReasoningError):
    """Raised when a primitive fails to execute."""
    pass

class IRParsingError(ReasoningError):
    """Raised when the LLM output cannot be parsed into valid IR."""
    pass

# --- Core Logic ---

class NeuroSymbolicEngine:
    """
    The core engine that parses LLM outputs into symbolic IR and executes them.
    """
    
    PRIMITIVE_PATTERN = re.compile(r"\[(DECOMPOSE|LOOKUP|COMPUTE|VERIFY|SYNTHESIZE)\]\s*(.*)")

    def __init__(self, tool_registry: Optional[Dict[str, Callable]] = None):
        """
        Initialize the engine with optional external tools.
        
        Args:
            tool_registry (Optional[Dict[str, Callable]]): Mapping of tool names to functions.
        """
        self.tool_registry = tool_registry if tool_registry else {}
        self.execution_history: List[ReasoningStep] = []
        logger.info("NeuroSymbolicEngine initialized.")

    def _parse_raw_output(self, llm_output: str) -> List[ReasoningStep]:
        """
        Parses raw LLM text output into a list of ReasoningSteps.
        
        Args:
            llm_output (str): The raw text generated by the LLM.
            
        Returns:
            List[ReasoningStep]: A list of parsed reasoning steps.
            
        Raises:
            IRParsingError: If no valid primitives are found.
        """
        steps = []
        lines = llm_output.strip().split('\n')
        step_counter = 0
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
                
            match = self.PRIMITIVE_PATTERN.match(line)
            if match:
                primitive_str, content = match.groups()
                try:
                    primitive = PrimitiveType[primitive_str]
                except KeyError:
                    primitive = PrimitiveType.UNKNOWN
                
                step = ReasoningStep(
                    step_id=step_counter,
                    primitive=primitive,
                    content=content.strip(),
                    args={} # Args can be parsed from content if structured
                )
                steps.append(step)
                step_counter += 1
                logger.debug(f"Parsed step: {primitive_str} - {content}")
        
        if not steps:
            logger.warning("No reasoning primitives found in LLM output.")
            raise IRParsingError("Failed to extract valid reasoning primitives from input.")
            
        return steps

    def _execute_step(self, step: ReasoningStep) -> str:
        """
        Executes a single reasoning step using internal logic or external tools.
        
        Args:
            step (ReasoningStep): The step to execute.
            
        Returns:
            str: The result of the execution.
        """
        logger.info(f"Executing Step {step.step_id}: [{step.primitive.value}] {step.content}")
        
        try:
            if step.primitive == PrimitiveType.COMPUTE:
                # Simulate calling a calculator tool
                if "calculator" in self.tool_registry:
                    step.result = self.tool_registry["calculator"](step.content)
                else:
                    # Mock computation for demonstration
                    step.result = f"Result_of({step.content})"
                    step.metadata["warning"] = "Used mock calculator"
            
            elif step.primitive == PrimitiveType.LOOKUP:
                # Simulate search
                step.result = f"Info_found_regarding('{step.content}')"
            
            elif step.primitive == PrimitiveType.VERIFY:
                # Logic to verify previous steps
                if self.execution_history:
                    last_step = self.execution_history[-1]
                    step.result = f"Verified_step_{last_step.step_id}"
                    step.is_verified = True
                else:
                    step.result = "Nothing_to_verify"
            
            elif step.primitive == PrimitiveType.DECOMPOSE:
                step.result = "Sub_tasks_generated"
            
            elif step.primitive == PrimitiveType.SYNTHESIZE:
                step.result = "Final_conclusion_draft"
            
            else:
                step.result = "No_action_taken"
                
            return step.result
            
        except Exception as e:
            logger.error(f"Error executing step {step.step_id}: {str(e)}")
            raise PrimitiveExecutionError(f"Failed to execute {step.primitive.value}: {str(e)}")

    def run_reasoning_chain(self, llm_output: str, interrupt_on: Optional[List[PrimitiveType]] = None) -> Dict[str, Any]:
        """
        Main entry point. Parses LLM output and executes the reasoning chain.
        
        Args:
            llm_output (str): The raw string from the LLM containing reasoning primitives.
            interrupt_on (Optional[List[PrimitiveType]]): List of primitives that trigger an interrupt/pause.
            
        Returns:
            Dict[str, Any]: The final execution trace and result.
        """
        if interrupt_on is None:
            interrupt_on = []
            
        self.execution_history = []
        
        try:
            # Data Validation: Input check
            if not isinstance(llm_output, str) or len(llm_output) < 5:
                raise ValueError("Input must be a non-empty string.")
            
            # 1. Parsing
            steps = self._parse_raw_output(llm_output)
            
            # 2. Execution Loop
            final_result = ""
            for step in steps:
                if step.primitive in interrupt_on:
                    logger.info(f"Interrupt triggered at step {step.step_id}")
                    step.metadata["interrupted"] = True
                    # In a real system, we might yield control here or wait for user input
                
                result = self._execute_step(step)
                self.execution_history.append(step)
                
                # Simple logic to capture the final synthesis result
                if step.primitive == PrimitiveType.SYNTHESIZE:
                    final_result = result
            
            return {
                "status": "success",
                "final_result": final_result,
                "trace": [s.to_dict() for s in self.execution_history],
                "steps_executed": len(self.execution_history)
            }
            
        except (IRParsingError, PrimitiveExecutionError, ValueError) as e:
            logger.exception("Reasoning chain failed.")
            return {
                "status": "failed",
                "error": str(e),
                "trace": [s.to_dict() for s in self.execution_history]
            }

# --- Helper Functions ---

def validate_ir_schema(data: Dict[str, Any]) -> bool:
    """
    Validates the structure of an external IR JSON object.
    
    Args:
        data (Dict): The data to validate.
        
    Returns:
        bool: True if valid, False otherwise.
    """
    required_keys = {"primitive", "content"}
    if not isinstance(data, dict):
        return False
    return required_keys.issubset(data.keys())

def format_trace_for_display(trace: List[Dict[str, Any]]) -> str:
    """
    Formats the execution trace into a human-readable string.
    
    Args:
        trace (List[Dict]): The list of step dictionaries.
        
    Returns:
        str: Formatted string.
    """
    output_lines = ["--- Reasoning Trace ---"]
    for step in trace:
        output_lines.append(
            f"Step {step.get('step_id', '?')}: "
            f"[{step.get('primitive', 'N/A')}] "
            f"Content: {step.get('content', 'N/A')} "
            f"-> Result: {step.get('result', 'Pending')}"
        )
    return "\n".join(output_lines)

# --- Usage Example ---
if __name__ == "__main__":
    # Simulated LLM Output containing Neuro-Symbolic IR
    mock_llm_response = """
    [DECOMPOSE] Analyze the requirements for the API integration.
    [LOOKUP] Find the latest documentation for Python requests library.
    [VERIFY] Ensure the authentication tokens are valid.
    [COMPUTE] Calculate the estimated latency based on packet size.
    [SYNTHESIZE] Generate the final implementation plan.
    """

    # Initialize Engine
    engine = NeuroSymbolicEngine()

    # Run Reasoning Chain
    # We want to interrupt/flag VERIFY steps for human review in this example
    result_data = engine.run_reasoning_chain(
        llm_output=mock_llm_response, 
        interrupt_on=[PrimitiveType.VERIFY]
    )

    # Display Results
    print(format_trace_for_display(result_data.get("trace", [])))
    print("\nFinal Status:", result_data["status"])