#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dart & Flutter 全领域知识节点数据"""

DART_CORE_NODES = [
    ("Dart核心语法", "Dart变量声明：var自动推断类型(var x=1则x为int)；final运行时常量只能赋值一次(final now=DateTime.now())；const编译时常量(const pi=3.14)。dynamic允许任意类型。late延迟初始化(late String name;首次读取前必须赋值)。类型推断:var list=[1,2,3]推断为List<int>"),
    ("Dart核心语法", "Dart字符串：单/双引号均可。多行'''或\"\"\"。插值:$var和${expr}。原始r'不转义\\n'。方法:contains/startsWith/endsWith/replaceAll/split/trim/padLeft/substring。StringBuffer高效拼接:var sb=StringBuffer()..write('a')..write('b');sb.toString()"),
    ("Dart核心语法", "Dart数值：int(64位)和double(64位浮点)继承num。int.parse('42')/double.parse('3.14')转换。位运算:&|^~<<>>。方法:abs/ceil/floor/round/clamp/compareTo。~/取整除。toStringAsFixed(2)保留小数"),
    ("Dart核心语法", "Dart运算符：算术+-*/%~/。关系==!=>>=<<=。逻辑&&||!。赋值=??=(空时赋值)。类型测试is/is!/as。级联..连续调用:paint..color=red..strokeWidth=5。空安全:?.安全调用,??空合并,!非空断言。展开...用于集合"),
    ("Dart核心语法", "Dart控制流：if/else。for/for-in/while/do-while。switch-case(Dart3支持模式匹配)。break/continue。assert(仅debug)。三元condition?a:b。标签循环:outer:for(...){for(...){break outer;}}"),
    ("Dart核心语法", "Dart函数：一等公民可赋值/传参/返回。位置参数func(int a,int b)。可选位置[int b=0]。命名参数{required int a,int b=0}。箭头=>。闭包:var adder(int n)=>(int x)=>x+n。typedef定义函数类型别名"),
    ("Dart核心语法", "Dart异常：try-catch-finally。throw抛出(throw Exception('msg'))。on Type catch(e,stackTrace)捕获。rethrow重抛。自定义:class AppError implements Exception{final String msg;AppError(this.msg);}"),
    ("Dart核心语法", "Dart导入：import 'package:flutter/material.dart'。as别名。show/hide选择性导入。deferred延迟加载:import 'heavy.dart' deferred as heavy;await heavy.loadLibrary()。export导出:export 'src/impl.dart' show PublicClass。_前缀库私有"),
    ("Dart类型系统", "Dart类型层次：Object所有非空基类。Object?所有可空基类。Null只有null。Never永不返回。void不使用返回值。num是int和double基类。所有类型都是对象。类型关系:int<num<Object<Object?"),
    ("Dart类型系统", "Dart空安全详解：String不可空(编译期保证)。String?可空。?.安全调用。??空合并。??=空时赋值。!非空断言(危险)。late延迟非空。流分析:if(s!=null){s.length//自动提升为String}。required命名参数必传"),
    ("Dart类型系统", "Dart泛型详解：类class Box<T>{T value;}。函数T first<T>(List<T> list)。约束<T extends Comparable<T>>。Dart泛型具体化:运行时可检查<int>[1] is List<int>为true。协变:List<Cat>可赋值给List<Animal>。多泛型参数Map<K,V>"),
    ("Dart类型系统", "Dart typedef类型别名：函数类型:typedef IntOp=int Function(int,int)。类类型:typedef Json=Map<String,dynamic>。泛型:typedef Callback<T>=void Function(T)。简化复杂类型声明提高可读性"),
    ("Dart异步编程", "Dart Future详解：Future<T>异步结果。创建:Future(()=>compute())/Future.value(42)/Future.delayed(Duration(s:1))。消费:then/catchError/whenComplete。async/await:var r=await future;配合try-catch。并行:Future.wait([f1(),f2()])。竞争:Future.any([f1(),f2()])"),
    ("Dart异步编程", "Dart Stream详解：Stream<T>异步事件序列。单订阅(listen一次)/广播(asBroadcastStream多次)。创建:Stream.fromIterable/periodic/StreamController。操作:map/where/expand/take/skip/distinct/asyncMap。消费:listen/await for/toList()"),
    ("Dart异步编程", "Dart StreamController：手动创建Stream。StreamController<int>()单订阅/.broadcast()广播。add/addError/close。sink属性。背压:onListen/onPause/onResume/onCancel。必须close()释放资源。配合StreamBuilder使用"),
    ("Dart异步编程", "Dart Isolate并发：单线程+Isolate多线程。compute()便捷:var r=await compute(heavyTask,data)新Isolate执行。Isolate.run()(Dart2.19+):var r=await Isolate.run(()=>fib(40))。不共享内存通过消息传递。ReceivePort/SendPort通信"),
    ("Dart集合", "Dart List详解：有序可重复。创建:[1,2,3]/List.filled(3,0)/List.generate(5,(i)=>i*2)/List.unmodifiable。增删:add/insert/remove/removeAt/removeWhere/clear。查询:contains/indexOf/any/every/firstWhere。排序:sort((a,b)=>a.compareTo(b))/shuffle"),
    ("Dart集合", "Dart Map详解：键值对。{'a':1}/Map.fromEntries/fromIterables。[key]取值/[key]=赋值/putIfAbsent/update/remove。containsKey/containsValue/keys/values/entries。forEach((k,v)=>...)。Map<String,dynamic>常用于JSON"),
    ("Dart集合", "Dart Iterable操作链：map/where/expand/fold/reduce/take/skip/takeWhile/skipWhile/every/any/first/last/toList/toSet。链式:list.where((x)=>x>0).map((x)=>x*2).toList()。惰性求值:除终端操作外不立即执行"),
    ("Dart集合", "Dart集合扩展运算符：展开:[...l1,...l2]合并/{{...s1,...s2}}/{...m1,...m2}。条件元素:[1,if(flag)2]。循环:[for(var i=0;i<5;i++)i*i]。Map展开后者覆盖同名键"),
    ("Dart面向对象", "Dart类与构造函数：class Point{double x,y;Point(this.x,this.y);}自动赋值。命名构造Point.origin():this(0,0)。工厂factory Singleton(){return _inst??=Singleton._();}。const构造编译时常量。初始化列表Point(x,y):assert(x>=0)"),
    ("Dart面向对象", "Dart继承与多态：extends单继承。super调用父类。@override重写。covariant协变。所有类继承Object。多态:Animal a=Cat();a.speak()//meow。runtimeType运行时类型"),
    ("Dart面向对象", "Dart抽象类与接口：abstract class不能实例化。抽象方法无方法体。implements必须实现所有方法(接口契约)。与extends区别:implements不继承实现。abstract interface class(Dart3)只能implements。可implements多个"),
    ("Dart面向对象", "Dart Mixin混入：mixin Swimmer{void swim()=>print('swimming');}。class Duck extends Bird with Swimmer,Flyer{}。on约束:mixin OnAnimal on Animal{}。with按序叠加后覆盖前。mixin class(Dart3)双用。用途:横切关注点"),
    ("Dart面向对象", "Dart getter/setter与运算符重载：get area=>w*h;set size(s){w=h=s;}。operator+(P o)=>P(x+o.x,y+o.y)。可重载:+-*/~/%==<>[]~&|^<<>>。==重载必须同时重载hashCode。call让对象像函数"),
    ("Dart面向对象", "Dart sealed密封类(Dart3)：sealed class Shape{}子类只能同库定义。编译器知道所有子类,switch穷举。class Circle extends Shape{}/class Square extends Shape{}。用途:状态/结果/AST等穷举类型"),
    ("Dart函数式编程", "Dart高阶函数与闭包：函数一等公民。高阶:接受/返回函数。闭包捕获外部变量。tearoff:list.forEach(print)。柯里化:add(int a)=>(int b)=>a+b。函数组合"),
    ("Dart函数式编程", "Dart不可变数据模式：const编译时不可变。final运行时不可变引用。List.unmodifiable运行时不可变集合。Records天然不可变。copyWith模式:User copyWith({String?name})=>User(name:name??this.name)。freezed库自动生成"),
    ("Dart包管理", "Dart pub包管理器：pubspec.yaml定义依赖。^1.2.3版本约束。dart pub get/upgrade/outdated。pubspec.lock锁定。pub.dev仓库。dependency_overrides本地覆盖。dev_dependencies开发依赖"),
    ("Dart包管理", "Dart核心库：dart:core(自动)/dart:async(Completer/StreamController/Timer)/dart:collection(Queue/LinkedList/HashMap)/dart:convert(json/utf8/base64)/dart:io(File/HttpClient/Socket/Process)/dart:math(Random/sin/cos)/dart:typed_data(Uint8List)"),
    ("Dart测试", "Dart单元测试(test包)：test('描述',(){expect(actual,matcher);})。group分组。setUp/tearDown。匹配器:equals/isTrue/isNull/isA<T>()/throwsA/contains/hasLength/greaterThan。异步:test('',()async{expect(await f(),isNotNull);})"),
    ("Dart测试", "Dart Mock测试(mockito)：@GenerateMocks([HttpClient])。when(mock.fetch(any)).thenReturn('data')。verify(mock.fetch('url')).called(1)。verifyNever/verifyNoMoreInteractions。build_runner生成。隔离外部依赖测试业务逻辑"),
]

FLUTTER_WIDGET_NODES = [
    ("Flutter Widget", "Flutter Widget树与渲染管线：Widget→Element→RenderObject三棵树。Widget不可变配置(轻量频繁重建)。Element管理生命周期。RenderObject布局绘制(复用)。setState触发:标记dirty→rebuild→diff最小化更新。Key帮助识别Widget身份"),
    ("Flutter Widget", "Flutter StatelessWidget：无状态。class W extends StatelessWidget{const W({super.key});@override Widget build(BuildContext context)=>Text('hello');}。适用纯展示。const避免rebuild。BuildContext提供树位置"),
    ("Flutter Widget", "Flutter StatefulWidget生命周期：createState→initState→didChangeDependencies→build→didUpdateWidget→deactivate→dispose。initState一次(初始化)。dispose释放(controller.dispose)。setState触发rebuild。mounted检查是否在树中"),
    ("Flutter Widget", "Flutter Key详解：ValueKey<T>(value)值匹配。ObjectKey(obj)实例匹配。UniqueKey()唯一。GlobalKey跨树访问State。用途:列表重排序保State/AnimatedSwitcher识别/Form标识"),
    ("Flutter Widget", "Flutter BuildContext：Element的抽象接口。Theme.of(context)/MediaQuery.of(context)/Navigator.of(context)向上查祖先。context.findAncestorWidgetOfExactType<T>()。注意:initState中不能dependOnInheritedWidget"),
    ("Flutter布局", "Flutter Flex布局(Row/Column)：Row水平/Column垂直。MainAxisAlignment:start/end/center/spaceBetween/spaceAround/spaceEvenly。CrossAxisAlignment:start/end/center/stretch。Expanded(flex:1)弹性。Flexible(fit:loose)。Spacer()间距"),
    ("Flutter布局", "Flutter Container与装饰：Container(width,height,padding,margin,decoration,alignment,constraints,child)。BoxDecoration:color/gradient/border/borderRadius/boxShadow/shape。EdgeInsets.all/symmetric/only/fromLTRB。transform:Matrix4"),
    ("Flutter布局", "Flutter Stack层叠：Stack(alignment,fit,children)。Positioned(left,top,right,bottom,child)定位。Positioned.fill铺满。IndexedStack只显示指定index。用途:头像+徽章/背景+内容/浮层"),
    ("Flutter布局", "Flutter约束布局原理：Constraints go down,Sizes go up,Parent sets position。tight约束min==max。loose约束min=0。unbounded max=infinity(ListView)。LayoutBuilder(builder:(ctx,constraints)=>...)获取父约束"),
    ("Flutter布局", "Flutter常用布局Widget：SizedBox固定大小/间距。ConstrainedBox约束。AspectRatio宽高比。FractionallySizedBox比例。FittedBox缩放适配。Wrap自动换行。Center居中。Padding内边距。IntrinsicHeight/Width内在尺寸"),
    ("Flutter布局", "Flutter响应式布局：MediaQuery.of(context).size屏幕尺寸。LayoutBuilder父约束动态布局。OrientationBuilder横竖屏。if(width>600)双栏else单栏。SafeArea避刘海。flutter_screenutil按设计稿适配"),
    ("Flutter状态管理", "Flutter setState与InheritedWidget：setState((){count++})触发rebuild。局限:只管当前Widget。InheritedWidget数据可被子树任意节点读取。Theme/MediaQuery基于此。updateShouldNotify控制更新"),
    ("Flutter状态管理", "Flutter Provider(推荐)：ChangeNotifierProvider(create:(_)=>Counter(),child:App())。Consumer<Counter>(builder:(ctx,c,_)=>Text('${c.value}'))。context.read<T>()不监听。context.watch<T>()监听。context.select精选。MultiProvider多个"),
    ("Flutter状态管理", "Flutter Riverpod(现代)：final counterProvider=StateProvider<int>((ref)=>0)。ConsumerWidget。ref.watch监听/ref.read读取。FutureProvider/StreamProvider/StateNotifierProvider/NotifierProvider。autoDispose自动释放。family参数化。编译时安全无BuildContext依赖"),
    ("Flutter状态管理", "Flutter Bloc(事件驱动)：Event→Bloc→State单向流。Bloc<Event,State>继承,on<E>((event,emit)=>emit(newState))。BlocProvider提供。BlocBuilder构建UI。BlocListener一次性副作用。context.read<Bloc>().add(Event())"),
    ("Flutter状态管理", "Flutter GetX(简单快速)：var count=0.obs响应式。Obx(()=>Text('${c.count}'))。GetxController。Get.put/Get.find注入。Get.to/Get.back导航。Get.snackbar/dialog。极简无context。大型项目可维护性需谨慎"),
    ("Flutter导航路由", "Flutter Navigator命令式：push(context,MaterialPageRoute(builder:(_)=>Page()))。pop(context,result)。pushReplacement替换。pushAndRemoveUntil清栈。命名路由pushNamed(context,'/detail',arguments:data)"),
    ("Flutter导航路由", "Flutter GoRouter声明式(推荐)：GoRouter(routes:[GoRoute(path:'/',builder:(_,__)=>Home())])。context.go('/detail/42')。pathParameters/queryParameters。redirect重定向守卫。ShellRoute嵌套布局。StatefulShellRoute底部导航保状态"),
    ("Flutter导航路由", "Flutter深层链接与路由守卫：Deep link:Android intent-filter/iOS Associated Domains。redirect:(ctx,state){if(!loggedIn)return'/login';return null;}。嵌套路由ShellRoute+子路由。CustomTransitionPage自定义转场动画"),
    ("Flutter动画", "Flutter隐式动画：AnimatedContainer(duration,width,color)属性变化自动动画。AnimatedOpacity/AnimatedPadding/AnimatedPositioned/AnimatedSwitcher/AnimatedCrossFade。TweenAnimationBuilder自定义隐式"),
    ("Flutter动画", "Flutter显式动画：AnimationController(vsync:this,duration)需TickerProviderStateMixin。Tween.animate(ctrl)。CurvedAnimation曲线。forward/reverse/repeat控制。FadeTransition/SlideTransition/RotationTransition/ScaleTransition"),
    ("Flutter动画", "Flutter Hero与页面转场：Hero(tag:'id',child:Image)两页面间飞行。tag必须匹配。PageRouteBuilder自定义转场。Staggered动画Interval控制时间段。flightShuttleBuilder自定义飞行Widget"),
    ("Flutter动画", "Flutter Rive与Lottie：Lottie:lottie包播放AE动画Lottie.asset('anim.json')。Rive:rive包交互式动画+状态机驱动。选择:简单用隐式/复杂序列用显式/设计师动画用Lottie或Rive"),
]

FLUTTER_ADVANCED_NODES = [
    ("Flutter主题样式", "Flutter ThemeData与Material3：MaterialApp(theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.blue))。darkTheme暗色。Theme.of(context).colorScheme.primary/secondary/surface。ThemeExtension自定义扩展主题"),
    ("Flutter主题样式", "Flutter文字与图标：TextStyle(fontSize,fontWeight,color,letterSpacing,height,fontFamily,decoration)。GoogleFonts。Icon(Icons.home,size,color)。Theme.of(context).textTheme.headlineMedium。RichText/TextSpan混合样式"),
    ("Flutter表单输入", "Flutter Form与验证：Form(key:_formKey,child:Column([TextFormField(validator:(v)=>v!.isEmpty?'必填':null,decoration:InputDecoration(labelText:'用户名'))]))。validate/save。TextEditingController。FocusNode焦点控制"),
    ("Flutter表单输入", "Flutter输入Widget：TextField/TextFormField文本。Checkbox/Radio/Switch选择。Slider滑块。DropdownButton下拉。showDatePicker/showTimePicker日期时间。Autocomplete自动补全。SearchBar搜索"),
    ("Flutter列表滚动", "Flutter ListView详解：ListView(children:[])少量。ListView.builder(itemCount,itemBuilder)懒加载。ListView.separated带分隔。ScrollController控制:offset/animateTo/jumpTo。physics:Bouncing/Clamping/NeverScrollable"),
    ("Flutter列表滚动", "Flutter GridView与瀑布流：GridView.count(crossAxisCount:2)。GridView.builder+SliverGridDelegate。GridView.extent(maxCrossAxisExtent)。flutter_staggered_grid_view瀑布流MasonryGridView。SliverGrid在CustomScrollView中"),
    ("Flutter列表滚动", "Flutter CustomScrollView与Sliver：CustomScrollView(slivers:[SliverAppBar(floating,expandedHeight,flexibleSpace),SliverList,SliverGrid,SliverToBoxAdapter])。SliverPersistentHeader吸顶。NestedScrollView嵌套"),
    ("Flutter列表滚动", "Flutter下拉刷新与加载更多：RefreshIndicator(onRefresh:()async{},child:ListView)。ScrollController监听到底加载。NotificationListener<ScrollNotification>。infinite_scroll_pagination分页。CupertinoSliverRefreshControl"),
    ("Flutter网络API", "Flutter HTTP请求(dio)：Dio(BaseOptions(baseUrl,connectTimeout,headers))。get/post/put/delete。拦截器interceptors.add(onRequest/onResponse/onError)。FormData文件上传。CancelToken取消。超时/重试"),
    ("Flutter网络API", "Flutter JSON序列化：手动:jsonDecode/jsonEncode+fromJson/toJson。代码生成(推荐):@JsonSerializable()类+json_annotation+json_serializable+build_runner。freezed自动生成不可变类+JSON。dart run build_runner build"),
    ("Flutter网络API", "Flutter REST API模式：Repository封装:class UserRepo{final Dio dio;Future<List<User>> getUsers()async{final r=await dio.get('/users');return(r.data as List).map(User.fromJson).toList();}}。sealed class Result<T>{}/Success/Failure错误封装。配合Provider注入"),
    ("Flutter网络API", "Flutter WebSocket实时通讯：web_socket_channel:WebSocketChannel.connect(uri)。stream.listen接收/sink.add发送/sink.close关闭。socket_io_client:io(url);socket.on/emit。StreamBuilder显示实时数据"),
    ("Flutter本地存储", "Flutter存储方案：SharedPreferences简单键值(设置)。sqflite SQLite(结构化)。hive NoSQL高性能(二进制)。drift类型安全ORM(复杂查询)。flutter_secure_storage安全(Keychain/Keystore)"),
    ("Flutter本地存储", "Flutter文件操作：path_provider获取路径:getApplicationDocumentsDirectory/getTemporaryDirectory。File读写:writeAsString/readAsString。Directory创建:create(recursive:true)。flutter_secure_storage存token"),
    ("Flutter平台通道", "Flutter MethodChannel：Dart:MethodChannel('com.app/battery').invokeMethod('getBatteryLevel')。Android(Kotlin):setMethodCallHandler。iOS(Swift):FlutterMethodChannel。用途:原生API如相机/蓝牙/传感器"),
    ("Flutter平台通道", "Flutter EventChannel与FFI：EventChannel原生向Dart发事件流(传感器)。FFI(dart:ffi)调用C/C++:DynamicLibrary.open+lookupFunction。Pigeon类型安全平台通道代码生成。ffigen自动生成FFI绑定"),
    ("Flutter测试", "Flutter Widget测试：testWidgets('desc',(tester)async{await tester.pumpWidget(App());expect(find.text('Hello'),findsOneWidget);await tester.tap(find.byType(Button));await tester.pump();})。find.text/byType/byKey。tester.enterText/drag"),
    ("Flutter测试", "Flutter集成测试：integration_test包。IntegrationTestWidgetsFlutterBinding.ensureInitialized()。pumpAndSettle等待动画完成。flutter test integration_test运行。takeScreenshot截图。完整用户流程测试"),
    ("Flutter测试", "Flutter Golden测试：expectLater(find.byType(W),matchesGoldenFile('goldens/w.png'))截图比对。flutter test --update-goldens更新基准。UI回归测试确保视觉一致。CI固定平台运行"),
    ("Flutter性能优化", "Flutter性能优化策略：const构造避免rebuild。RepaintBoundary隔离重绘。ListView.builder懒加载。图片:CachedNetworkImage/预加载precacheImage。避免build()中创建对象。Isolate.run移CPU任务。DevTools分析"),
    ("Flutter性能优化", "Flutter构建优化与减包：Tree shaking移除未用代码。--split-debug-info减体积。--obfuscate混淆。--split-per-abi分包。flutter build --analyze-size分析。Memory分析泄漏。Stream未cancel/Controller未dispose常见泄漏"),
    ("Flutter国际化", "Flutter国际化(i18n)：flutter_localizations+intl。arb文件定义翻译。flutter gen-l10n生成。AppLocalizations.of(context)!.hello('World')使用。支持复数/性别/占位符。supportedLocales配置"),
    ("Flutter架构模式", "Flutter Clean Architecture：Presentation(UI+State)/Domain(Entity+UseCase+Repo接口)/Data(Repo实现+DataSource+Model)。依赖规则:外层依赖内层。UseCase封装业务。get_it/injectable依赖注入。可测试可替换"),
    ("Flutter架构模式", "Flutter MVVM：Model数据+Repo。View Widget只UI。ViewModel ChangeNotifier/StateNotifier持有状态+逻辑。View通过Provider监听VM。命令模式:VM暴露fetch/create/delete。UI逻辑分离可测试"),
    ("Flutter架构模式", "Flutter Repository与依赖注入：abstract class UserRepo{Future<List<User>> getUsers();}实现封装API+缓存。get_it注入:GetIt.I.registerLazySingleton<UserRepo>(()=>Impl(api,db))。测试替换Mock"),
    ("Flutter插件开发", "Flutter Package与Plugin：Package纯Dart:flutter create --template=package。Plugin含原生:--template=plugin --platforms=android,ios。Federated Plugin:app-facing/platform_interface/平台实现。dart pub publish发布"),
    ("Flutter多平台", "Flutter Web：flutter build web。渲染器:CanvasKit(Skia全功能)/HTML(轻量DOM)。usePathUrlStrategy路径路由。kIsWeb判断。dart:io不可用。条件导入适配平台差异"),
    ("Flutter多平台", "Flutter桌面(Win/Mac/Linux)：flutter create --platforms=windows,macos,linux。window_manager窗口管理。PlatformMenuBar菜单。file_picker文件对话框。Platform.isMacOS/isWindows判断。msix/dmg打包"),
    ("Flutter DevTools", "Flutter DevTools：Widget Inspector查看树/属性。Layout Explorer可视化布局。Performance帧率/Jank。Timeline渲染管线。Memory泄漏检测。Network HTTP监控。CPU Profiler。debugPrint/debugDumpApp()"),
]

# 关系定义: (src_keyword, tgt_keyword, type, strength)
RELATIONS = [
    ("Dart变量声明", "Dart空安全详解", "depends_on", 0.9),
    ("Dart变量声明", "Dart类型层次", "depends_on", 0.85),
    ("Dart函数", "Dart高阶函数与闭包", "extends", 0.95),
    ("Dart类与构造函数", "Dart继承与多态", "extends", 0.95),
    ("Dart类与构造函数", "Dart抽象类与接口", "extends", 0.9),
    ("Dart类与构造函数", "Dart Mixin混入", "extends", 0.9),
    ("Dart类与构造函数", "Dart getter/setter", "extends", 0.85),
    ("Dart泛型详解", "Dart List详解", "depends_on", 0.9),
    ("Dart类型层次", "Dart空安全详解", "extends", 0.9),
    ("Dart Future详解", "Dart Stream详解", "extends", 0.85),
    ("Dart Stream详解", "Dart StreamController", "extends", 0.95),
    ("Dart Isolate并发", "Dart Future详解", "depends_on", 0.8),
    ("Dart List详解", "Dart Iterable操作链", "extends", 0.9),
    ("Dart sealed密封类", "Dart抽象类与接口", "extends", 0.85),
    ("Dart不可变数据", "Dart高阶函数", "complements", 0.8),
    ("Dart pub包管理", "Dart核心库", "manages", 0.9),
    ("Dart单元测试", "Dart Mock测试", "extends", 0.9),
    ("Flutter Widget树", "Flutter StatelessWidget", "parent_of", 0.95),
    ("Flutter Widget树", "Flutter StatefulWidget", "parent_of", 0.95),
    ("Flutter Widget树", "Flutter Key详解", "depends_on", 0.9),
    ("Flutter Widget树", "Flutter BuildContext", "depends_on", 0.9),
    ("Flutter StatefulWidget", "Flutter setState与InheritedWidget", "extends", 0.95),
    ("Flutter Flex布局", "Flutter约束布局原理", "implements", 0.9),
    ("Flutter Container", "Flutter约束布局原理", "implements", 0.85),
    ("Flutter Stack层叠", "Flutter约束布局原理", "implements", 0.85),
    ("Flutter响应式布局", "Flutter约束布局原理", "extends", 0.8),
    ("Flutter setState", "Flutter Provider", "extends", 0.95),
    ("Flutter Provider", "Flutter Riverpod", "evolves_to", 0.9),
    ("Flutter Provider", "Flutter Bloc", "alternative", 0.8),
    ("Flutter Provider", "Flutter GetX", "alternative", 0.75),
    ("Flutter Navigator命令式", "Flutter GoRouter", "evolves_to", 0.9),
    ("Flutter GoRouter", "Flutter深层链接", "extends", 0.9),
    ("Flutter隐式动画", "Flutter显式动画", "extends", 0.9),
    ("Flutter显式动画", "Flutter Hero", "extends", 0.85),
    ("Flutter HTTP请求", "Flutter JSON序列化", "depends_on", 0.95),
    ("Flutter JSON序列化", "Flutter REST API", "extends", 0.9),
    ("Flutter REST API", "Flutter Repository与依赖注入", "implements", 0.9),
    ("Flutter WebSocket", "Flutter HTTP请求", "complements", 0.8),
    ("Flutter存储方案", "Flutter文件操作", "complements", 0.85),
    ("Flutter MethodChannel", "Flutter EventChannel", "complements", 0.9),
    ("Flutter MethodChannel", "Flutter Package与Plugin", "depends_on", 0.85),
    ("Dart单元测试", "Flutter Widget测试", "extends", 0.85),
    ("Flutter Widget测试", "Flutter集成测试", "extends", 0.9),
    ("Flutter集成测试", "Flutter Golden测试", "complements", 0.8),
    ("Flutter Clean Architecture", "Flutter Repository与依赖注入", "depends_on", 0.9),
    ("Flutter MVVM", "Flutter Provider", "depends_on", 0.85),
    ("Flutter性能优化策略", "Flutter构建优化", "extends", 0.9),
    ("Flutter ThemeData", "Flutter文字与图标", "extends", 0.85),
    ("Flutter Form与验证", "Flutter输入Widget", "depends_on", 0.9),
    ("Flutter ListView详解", "Flutter下拉刷新", "extends", 0.9),
    ("Flutter GridView", "Flutter CustomScrollView", "depends_on", 0.85),
    ("Flutter ListView详解", "Flutter CustomScrollView", "depends_on", 0.85),
    ("Flutter DevTools", "Flutter性能优化策略", "complements", 0.9),
    ("Dart异步编程", "Flutter网络API", "enables", 0.9),
    ("Dart Isolate", "Flutter性能优化", "enables", 0.85),
    ("Dart面向对象", "Flutter Widget", "enables", 0.9),
]
